namespace :bootstrap_3  do
  desc "Seed Data For Bootstrap 3"
  task :seed => :environment do
    Category.find_or_create_by({ id: 33, name: "Tabs" })
    Category.find_or_create_by({ id: 34, name: "Pills" })
    Category.find_or_create_by({ id: 35, name: "Panels" })
    Category.find_or_create_by({ id: 36, name: "Wells" })
    Category.find_or_create_by({ id: 37, name: "Badges" })

    DefaultVariable.where(version: "3.3").delete_all
    DefaultVariable.create([
      { name: "$body-bg", value: "#fff", position: 1, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$gray-base", value: "#000", position: 2, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$gray-darker", value: "lighten($gray-base, 13.5%)", position: 3, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$gray-dark", value: "lighten($gray-base, 20%)", position: 4, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$gray", value: "lighten($gray-base, 33.5%)", position: 5, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$gray-light", value: "lighten($gray-base, 46.7%)", position: 6, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$gray-lighter", value: "lighten($gray-base, 93.5%)", position: 7, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$brand-primary", value: "darken(#428bca, 6.5%)", position: 8, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$brand-success", value: "#5cb85c", position: 9, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$brand-info", value: "#5bc0de", position: 10, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$brand-warning", value: "#f0ad4e", position: 11, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$brand-danger", value: "#d9534f", position: 12, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$link-color", value: "$brand-primary", position: 13, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$link-hover-color", value: "darken($link-color, 15%)", position: 14, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$link-hover-decoration", value: "underline", position: 15, category_id: 2, framework: "bootstrap", version: "3.3" },
      { name: "$screen-xs", value: "480px", position: 16, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-xs-min", value: "$screen-xs", position: 17, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-phone", value: "$screen-xs-min", position: 18, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-sm", value: "768px", position: 19, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-sm-min", value: "$screen-sm", position: 20, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-tablet", value: "$screen-sm-min", position: 21, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-md", value: "992px", position: 22, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-md-min", value: "$screen-md", position: 23, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-desktop", value: "$screen-md-min", position: 24, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-lg", value: "1200px", position: 25, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-lg-min", value: "$screen-lg", position: 26, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-lg-desktop", value: "$screen-lg-min", position: 27, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-xs-max", value: "($screen-sm-min - 1)", position: 28, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-sm-max", value: "($screen-md-min - 1)", position: 29, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$screen-md-max", value: "($screen-lg-min - 1)", position: 30, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$grid-columns", value: "12", position: 31, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$grid-gutter-width", value: "30px", position: 32, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$grid-float-breakpoint", value: "$screen-sm-min", position: 33, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$grid-float-breakpoint-max", value: "($grid-float-breakpoint - 1)", position: 34, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$container-tablet", value: "(720px + $grid-gutter-width)", position: 35, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$container-sm", value: "$container-tablet", position: 36, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$container-desktop", value: "(940px + $grid-gutter-width)", position: 37, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$container-md", value: "$container-desktop", position: 38, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$container-large-desktop", value: "(1140px + $grid-gutter-width)", position: 39, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$container-lg", value: "$container-large-desktop", position: 40, category_id: 7, framework: "bootstrap", version: "3.3" },
      { name: "$text-color", value: "$gray-dark", position: 41, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-family-sans-serif", value: "\"Helvetica Neue\", Helvetica, Arial, sans-serif", position: 42, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-family-serif", value: "Georgia, \"Times New Roman\", Times, serif", position: 43, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-family-monospace", value: "Menlo, Monaco, Consolas, \"Courier New\", monospace", position: 44, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-family-base", value: "$font-family-sans-serif", position: 45, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-size-base", value: "14px", position: 46, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-size-large", value: "ceil(($font-size-base * 1.25))", position: 47, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-size-small", value: "ceil(($font-size-base * 0.85))", position: 48, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-size-h1", value: "floor(($font-size-base * 2.6))", position: 49, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-size-h2", value: "floor(($font-size-base * 2.15))", position: 50, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-size-h3", value: "ceil(($font-size-base * 1.7))", position: 51, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-size-h4", value: "ceil(($font-size-base * 1.25))", position: 52, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-size-h5", value: "$font-size-base", position: 53, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$font-size-h6", value: "ceil(($font-size-base * 0.85))", position: 54, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$line-height-base", value: "1.428571429", position: 55, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$line-height-computed", value: "floor(($font-size-base * $line-height-base))", position: 56, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$headings-font-family", value: "inherit", position: 57, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$headings-font-weight", value: "500", position: 58, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$headings-line-height", value: "1.1", position: 59, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$headings-color", value: "inherit", position: 60, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$component-offset-horizontal", value: "180px", position: 61, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$text-muted", value: "$gray-light", position: 62, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$abbr-border-color", value: "$gray-light", position: 63, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$headings-small-color", value: "$gray-light", position: 64, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$blockquote-small-color", value: "$gray-light", position: 65, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$blockquote-font-size", value: "($font-size-base * 1.25)", position: 66, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$blockquote-border-color", value: "$gray-lighter", position: 67, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$page-header-border-color", value: "$gray-lighter", position: 68, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$dl-horizontal-offset", value: "$component-offset-horizontal", position: 69, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$dl-horizontal-breakpoint", value: "$grid-float-breakpoint", position: 70, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$hr-border", value: "$gray-lighter", position: 71, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$icon-font-name", value: "\"glyphicons-halflings-regular\"", position: 73, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$icon-font-svg-id", value: "\"glyphicons_halflingsregular\"", position: 74, category_id: 8, framework: "bootstrap", version: "3.3" },
      { name: "$padding-base-vertical", value: "6px", position: 75, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$padding-base-horizontal", value: "12px", position: 76, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$padding-large-vertical", value: "10px", position: 77, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$padding-large-horizontal", value: "16px", position: 78, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$padding-small-vertical", value: "5px", position: 79, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$padding-small-horizontal", value: "10px", position: 80, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$padding-xs-vertical", value: "1px", position: 81, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$padding-xs-horizontal", value: "5px", position: 82, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$line-height-large", value: "1.3333333", position: 83, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$line-height-small", value: "1.5", position: 84, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$border-radius-base", value: "4px", position: 85, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$border-radius-large", value: "6px", position: 86, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$border-radius-small", value: "3px", position: 87, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$component-active-color", value: "#fff", position: 88, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$component-active-bg", value: "$brand-primary", position: 89, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$caret-width-base", value: "4px", position: 90, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$caret-width-large", value: "5px", position: 91, category_id: 9, framework: "bootstrap", version: "3.3" },
      { name: "$table-cell-padding", value: "8px", position: 92, category_id: 10, framework: "bootstrap", version: "3.3" },
      { name: "$table-condensed-cell-padding", value: "5px", position: 93, category_id: 10, framework: "bootstrap", version: "3.3" },
      { name: "$table-bg", value: "transparent", position: 94, category_id: 10, framework: "bootstrap", version: "3.3" },
      { name: "$table-bg-accent", value: "#f9f9f9", position: 95, category_id: 10, framework: "bootstrap", version: "3.3" },
      { name: "$table-bg-hover", value: "#f5f5f5", position: 96, category_id: 10, framework: "bootstrap", version: "3.3" },
      { name: "$table-bg-active", value: "$table-bg-hover", position: 97, category_id: 10, framework: "bootstrap", version: "3.3" },
      { name: "$table-border-color", value: "#ddd", position: 98, category_id: 10, framework: "bootstrap", version: "3.3" },
      { name: "$btn-font-weight", value: "normal", position: 99, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-default-color", value: "#333", position: 100, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-default-bg", value: "#fff", position: 101, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-default-border", value: "#ccc", position: 102, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-primary-color", value: "#fff", position: 103, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-primary-bg", value: "$brand-primary", position: 104, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-primary-border", value: "darken($btn-primary-bg, 5%)", position: 105, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-success-color", value: "#fff", position: 106, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-success-bg", value: "$brand-success", position: 107, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-success-border", value: "darken($btn-success-bg, 5%)", position: 108, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-info-color", value: "#fff", position: 109, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-info-bg", value: "$brand-info", position: 110, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-info-border", value: "darken($btn-info-bg, 5%)", position: 111, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-warning-color", value: "#fff", position: 112, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-warning-bg", value: "$brand-warning", position: 113, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-warning-border", value: "darken($btn-warning-bg, 5%)", position: 114, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-danger-color", value: "#fff", position: 115, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-danger-bg", value: "$brand-danger", position: 116, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-danger-border", value: "darken($btn-danger-bg, 5%)", position: 117, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-link-disabled-color", value: "$gray-light", position: 118, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-border-radius-base", value: "$border-radius-base", position: 119, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-border-radius-large", value: "$border-radius-large", position: 120, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$btn-border-radius-small", value: "$border-radius-small", position: 121, category_id: 11, framework: "bootstrap", version: "3.3" },
      { name: "$input-bg", value: "#fff", position: 122, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-bg-disabled", value: "$gray-lighter", position: 123, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-color", value: "$gray", position: 124, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-border", value: "#ccc", position: 125, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-border-radius", value: "$border-radius-base", position: 126, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-border-radius-large", value: "$border-radius-large", position: 127, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-border-radius-small", value: "$border-radius-small", position: 128, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-border-focus", value: "#66afe9", position: 129, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-color-placeholder", value: "#999", position: 130, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-height-base", value: "($line-height-computed + ($padding-base-vertical * 2) + 2)", position: 131, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-height-large", value: "(ceil($font-size-large * $line-height-large) + ($padding-large-vertical * 2) + 2)", position: 132, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-height-small", value: "(floor($font-size-small * $line-height-small) + ($padding-small-vertical * 2) + 2)", position: 133, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$form-group-margin-bottom", value: "15px", position: 134, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$legend-color", value: "$gray-dark", position: 135, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$legend-border-color", value: "#e5e5e5", position: 136, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-group-addon-bg", value: "$gray-lighter", position: 137, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$input-group-addon-border-color", value: "$input-border", position: 138, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$cursor-disabled", value: "not-allowed", position: 139, category_id: 12, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-bg", value: "#fff", position: 140, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-border", value: "rgba(0,0,0,.15)", position: 141, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-fallback-border", value: "#ccc", position: 142, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-divider-bg", value: "#e5e5e5", position: 143, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-link-color", value: "$gray-dark", position: 144, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-link-hover-color", value: "darken($gray-dark, 5%)", position: 145, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-link-hover-bg", value: "#f5f5f5", position: 146, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-link-active-color", value: "$component-active-color", position: 147, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-link-active-bg", value: "$component-active-bg", position: 148, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-link-disabled-color", value: "$gray-light", position: 149, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-header-color", value: "$gray-light", position: 150, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$dropdown-caret-color", value: "#000", position: 151, category_id: 13, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-height", value: "50px", position: 152, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-margin-bottom", value: "$line-height-computed", position: 153, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-border-radius", value: "$border-radius-base", position: 154, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-padding-horizontal", value: "floor(($grid-gutter-width / 2))", position: 155, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-padding-vertical", value: "(($navbar-height - $line-height-computed) / 2)", position: 156, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-collapse-max-height", value: "340px", position: 157, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-color", value: "#777", position: 158, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-bg", value: "#f8f8f8", position: 159, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-border", value: "darken($navbar-default-bg, 6.5%)", position: 160, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-link-color", value: "#777", position: 161, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-link-hover-color", value: "#333", position: 162, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-link-hover-bg", value: "transparent", position: 163, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-link-active-color", value: "#555", position: 164, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-link-active-bg", value: "darken($navbar-default-bg, 6.5%)", position: 165, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-link-disabled-color", value: "#ccc", position: 166, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-link-disabled-bg", value: "transparent", position: 167, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-brand-color", value: "$navbar-default-link-color", position: 168, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-brand-hover-color", value: "darken($navbar-default-brand-color, 10%)", position: 169, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-brand-hover-bg", value: "transparent", position: 170, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-toggle-hover-bg", value: "#ddd", position: 171, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-toggle-icon-bar-bg", value: "#888", position: 172, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-default-toggle-border-color", value: "#ddd", position: 173, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-color", value: "lighten($gray-light, 15%)", position: 174, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-bg", value: "#222", position: 175, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-border", value: "darken($navbar-inverse-bg, 10%)", position: 176, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-link-color", value: "lighten($gray-light, 15%)", position: 177, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-link-hover-color", value: "#fff", position: 178, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-link-hover-bg", value: "transparent", position: 179, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-link-active-color", value: "$navbar-inverse-link-hover-color", position: 180, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-link-active-bg", value: "darken($navbar-inverse-bg, 10%)", position: 181, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-link-disabled-color", value: "#444", position: 182, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-link-disabled-bg", value: "transparent", position: 183, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-brand-color", value: "$navbar-inverse-link-color", position: 184, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-brand-hover-color", value: "#fff", position: 185, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-brand-hover-bg", value: "transparent", position: 186, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-toggle-hover-bg", value: "#333", position: 187, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-toggle-icon-bar-bg", value: "#fff", position: 188, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$navbar-inverse-toggle-border-color", value: "#333", position: 189, category_id: 14, framework: "bootstrap", version: "3.3" },
      { name: "$nav-link-padding", value: "10px 15px", position: 190, category_id: 15, framework: "bootstrap", version: "3.3" },
      { name: "$nav-link-hover-bg", value: "$gray-lighter", position: 191, category_id: 15, framework: "bootstrap", version: "3.3" },
      { name: "$nav-disabled-link-color", value: "$gray-light", position: 192, category_id: 15, framework: "bootstrap", version: "3.3" },
      { name: "$nav-disabled-link-hover-color", value: "$gray-light", position: 193, category_id: 15, framework: "bootstrap", version: "3.3" },
      { name: "$nav-tabs-border-color", value: "#ddd", position: 194, category_id: 33, framework: "bootstrap", version: "3.3" },
      { name: "$nav-tabs-link-hover-border-color", value: "$gray-lighter", position: 195, category_id: 33, framework: "bootstrap", version: "3.3" },
      { name: "$nav-tabs-active-link-hover-bg", value: "$body-bg", position: 196, category_id: 33, framework: "bootstrap", version: "3.3" },
      { name: "$nav-tabs-active-link-hover-color", value: "$gray", position: 197, category_id: 33, framework: "bootstrap", version: "3.3" },
      { name: "$nav-tabs-active-link-hover-border-color", value: "#ddd", position: 198, category_id: 33, framework: "bootstrap", version: "3.3" },
      { name: "$nav-tabs-justified-link-border-color", value: "#ddd", position: 199, category_id: 33, framework: "bootstrap", version: "3.3" },
      { name: "$nav-tabs-justified-active-link-border-color", value: "$body-bg", position: 200, category_id: 33, framework: "bootstrap", version: "3.3" },
      { name: "$nav-pills-border-radius", value: "$border-radius-base", position: 201, category_id: 34, framework: "bootstrap", version: "3.3" },
      { name: "$nav-pills-active-link-hover-bg", value: "$component-active-bg", position: 202, category_id: 34, framework: "bootstrap", version: "3.3" },
      { name: "$nav-pills-active-link-hover-color", value: "$component-active-color", position: 203, category_id: 34, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-color", value: "$link-color", position: 204, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-bg", value: "#fff", position: 205, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-border", value: "#ddd", position: 206, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-hover-color", value: "$link-hover-color", position: 207, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-hover-bg", value: "$gray-lighter", position: 208, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-hover-border", value: "#ddd", position: 209, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-active-color", value: "#fff", position: 210, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-active-bg", value: "$brand-primary", position: 211, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-active-border", value: "$brand-primary", position: 212, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-disabled-color", value: "$gray-light", position: 213, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-disabled-bg", value: "#fff", position: 214, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pagination-disabled-border", value: "#ddd", position: 215, category_id: 16, framework: "bootstrap", version: "3.3" },
      { name: "$pager-bg", value: "$pagination-bg", position: 216, category_id: 17, framework: "bootstrap", version: "3.3" },
      { name: "$pager-border", value: "$pagination-border", position: 217, category_id: 17, framework: "bootstrap", version: "3.3" },
      { name: "$pager-border-radius", value: "15px", position: 218, category_id: 17, framework: "bootstrap", version: "3.3" },
      { name: "$pager-hover-bg", value: "$pagination-hover-bg", position: 219, category_id: 17, framework: "bootstrap", version: "3.3" },
      { name: "$pager-active-bg", value: "$pagination-active-bg", position: 220, category_id: 17, framework: "bootstrap", version: "3.3" },
      { name: "$pager-active-color", value: "$pagination-active-color", position: 221, category_id: 17, framework: "bootstrap", version: "3.3" },
      { name: "$pager-disabled-color", value: "$pagination-disabled-color", position: 222, category_id: 17, framework: "bootstrap", version: "3.3" },
      { name: "$jumbotron-padding", value: "30px", position: 223, category_id: 18, framework: "bootstrap", version: "3.3" },
      { name: "$jumbotron-color", value: "inherit", position: 224, category_id: 18, framework: "bootstrap", version: "3.3" },
      { name: "$jumbotron-bg", value: "$gray-lighter", position: 225, category_id: 18, framework: "bootstrap", version: "3.3" },
      { name: "$jumbotron-heading-color", value: "inherit", position: 226, category_id: 18, framework: "bootstrap", version: "3.3" },
      { name: "$jumbotron-font-size", value: "ceil(($font-size-base * 1.5))", position: 227, category_id: 18, framework: "bootstrap", version: "3.3" },
      { name: "$jumbotron-heading-font-size", value: "ceil(($font-size-base * 4.5))", position: 228, category_id: 18, framework: "bootstrap", version: "3.3" },
      { name: "$state-success-text", value: "#3c763d", position: 229, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-success-bg", value: "#dff0d8", position: 230, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-success-border", value: "darken(adjust-hue($state-success-bg, -10), 5%)", position: 231, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-info-text", value: "#31708f", position: 232, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-info-bg", value: "#d9edf7", position: 233, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-info-border", value: "darken(adjust-hue($state-info-bg, -10), 7%)", position: 234, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-warning-text", value: "#8a6d3b", position: 235, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-warning-bg", value: "#fcf8e3", position: 236, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-warning-border", value: "darken(adjust-hue($state-warning-bg, -10), 5%)", position: 237, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-danger-text", value: "#a94442", position: 238, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-danger-bg", value: "#f2dede", position: 239, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$state-danger-border", value: "darken(adjust-hue($state-danger-bg, -10), 5%)", position: 240, category_id: 19, framework: "bootstrap", version: "3.3" },
      { name: "$tooltip-max-width", value: "200px", position: 241, category_id: 21, framework: "bootstrap", version: "3.3" },
      { name: "$tooltip-color", value: "#fff", position: 242, category_id: 21, framework: "bootstrap", version: "3.3" },
      { name: "$tooltip-bg", value: "#000", position: 243, category_id: 21, framework: "bootstrap", version: "3.3" },
      { name: "$tooltip-opacity", value: "0.9", position: 244, category_id: 21, framework: "bootstrap", version: "3.3" },
      { name: "$tooltip-arrow-width", value: "5px", position: 245, category_id: 21, framework: "bootstrap", version: "3.3" },
      { name: "$tooltip-arrow-color", value: "$tooltip-bg", position: 246, category_id: 21, framework: "bootstrap", version: "3.3" },
      { name: "$popover-bg", value: "#fff", position: 247, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$popover-max-width", value: "276px", position: 248, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$popover-border-color", value: "rgba(0,0,0,.2)", position: 249, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$popover-fallback-border-color", value: "#ccc", position: 250, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$popover-title-bg", value: "darken($popover-bg, 3%)", position: 251, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$popover-arrow-width", value: "10px", position: 252, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$popover-arrow-color", value: "$popover-bg", position: 253, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$popover-arrow-outer-width", value: "($popover-arrow-width + 1)", position: 254, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$popover-arrow-outer-color", value: "fade_in($popover-border-color, 0.05)", position: 255, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$popover-arrow-outer-fallback-color", value: "darken($popover-fallback-border-color, 20%)", position: 256, category_id: 22, framework: "bootstrap", version: "3.3" },
      { name: "$label-default-bg", value: "$gray-light", position: 257, category_id: 23, framework: "bootstrap", version: "3.3" },
      { name: "$label-primary-bg", value: "$brand-primary", position: 258, category_id: 23, framework: "bootstrap", version: "3.3" },
      { name: "$label-success-bg", value: "$brand-success", position: 259, category_id: 23, framework: "bootstrap", version: "3.3" },
      { name: "$label-info-bg", value: "$brand-info", position: 260, category_id: 23, framework: "bootstrap", version: "3.3" },
      { name: "$label-warning-bg", value: "$brand-warning", position: 261, category_id: 23, framework: "bootstrap", version: "3.3" },
      { name: "$label-danger-bg", value: "$brand-danger", position: 262, category_id: 23, framework: "bootstrap", version: "3.3" },
      { name: "$label-color", value: "#fff", position: 263, category_id: 23, framework: "bootstrap", version: "3.3" },
      { name: "$label-link-hover-color", value: "#fff", position: 264, category_id: 23, framework: "bootstrap", version: "3.3" },
      { name: "$modal-inner-padding", value: "15px", position: 265, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-title-padding", value: "15px", position: 266, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-title-line-height", value: "$line-height-base", position: 267, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-content-bg", value: "#fff", position: 268, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-content-border-color", value: "rgba(0,0,0,.2)", position: 269, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-content-fallback-border-color", value: "#999", position: 270, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-backdrop-bg", value: "#000", position: 271, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-backdrop-opacity", value: "0.5", position: 272, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-header-border-color", value: "#e5e5e5", position: 273, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-footer-border-color", value: "$modal-header-border-color", position: 274, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-lg", value: "900px", position: 275, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-md", value: "600px", position: 276, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$modal-sm", value: "300px", position: 277, category_id: 24, framework: "bootstrap", version: "3.3" },
      { name: "$alert-padding", value: "15px", position: 278, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-border-radius", value: "$border-radius-base", position: 279, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-link-font-weight", value: "bold", position: 280, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-success-bg", value: "$state-success-bg", position: 281, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-success-text", value: "$state-success-text", position: 282, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-success-border", value: "$state-success-border", position: 283, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-info-bg", value: "$state-info-bg", position: 284, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-info-text", value: "$state-info-text", position: 285, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-info-border", value: "$state-info-border", position: 286, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-warning-bg", value: "$state-warning-bg", position: 287, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-warning-text", value: "$state-warning-text", position: 288, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-warning-border", value: "$state-warning-border", position: 289, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-danger-bg", value: "$state-danger-bg", position: 290, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-danger-text", value: "$state-danger-text", position: 291, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$alert-danger-border", value: "$state-danger-border", position: 292, category_id: 25, framework: "bootstrap", version: "3.3" },
      { name: "$progress-bg", value: "#f5f5f5", position: 293, category_id: 26, framework: "bootstrap", version: "3.3" },
      { name: "$progress-bar-color", value: "#fff", position: 294, category_id: 26, framework: "bootstrap", version: "3.3" },
      { name: "$progress-border-radius", value: "$border-radius-base", position: 295, category_id: 26, framework: "bootstrap", version: "3.3" },
      { name: "$progress-bar-bg", value: "$brand-primary", position: 296, category_id: 26, framework: "bootstrap", version: "3.3" },
      { name: "$progress-bar-success-bg", value: "$brand-success", position: 297, category_id: 26, framework: "bootstrap", version: "3.3" },
      { name: "$progress-bar-warning-bg", value: "$brand-warning", position: 298, category_id: 26, framework: "bootstrap", version: "3.3" },
      { name: "$progress-bar-danger-bg", value: "$brand-danger", position: 299, category_id: 26, framework: "bootstrap", version: "3.3" },
      { name: "$progress-bar-info-bg", value: "$brand-info", position: 300, category_id: 26, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-bg", value: "#fff", position: 301, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-border", value: "#ddd", position: 302, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-border-radius", value: "$border-radius-base", position: 303, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-hover-bg", value: "#f5f5f5", position: 304, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-active-color", value: "$component-active-color", position: 305, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-active-bg", value: "$component-active-bg", position: 306, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-active-border", value: "$list-group-active-bg", position: 307, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-active-text-color", value: "lighten($list-group-active-bg, 40%)", position: 308, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-disabled-color", value: "$gray-light", position: 309, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-disabled-bg", value: "$gray-lighter", position: 310, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-disabled-text-color", value: "$list-group-disabled-color", position: 311, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-link-color", value: "#555", position: 312, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-link-hover-color", value: "$list-group-link-color", position: 313, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$list-group-link-heading-color", value: "#333", position: 314, category_id: 27, framework: "bootstrap", version: "3.3" },
      { name: "$panel-bg", value: "#fff", position: 315, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-body-padding", value: "15px", position: 316, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-heading-padding", value: "10px 15px", position: 317, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-footer-padding", value: "$panel-heading-padding", position: 318, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-border-radius", value: "$border-radius-base", position: 319, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-inner-border", value: "#ddd", position: 320, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-footer-bg", value: "#f5f5f5", position: 321, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-default-text", value: "$gray-dark", position: 322, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-default-border", value: "#ddd", position: 323, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-default-heading-bg", value: "#f5f5f5", position: 324, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-primary-text", value: "#fff", position: 325, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-primary-border", value: "$brand-primary", position: 326, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-primary-heading-bg", value: "$brand-primary", position: 327, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-success-text", value: "$state-success-text", position: 328, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-success-border", value: "$state-success-border", position: 329, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-success-heading-bg", value: "$state-success-bg", position: 330, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-info-text", value: "$state-info-text", position: 331, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-info-border", value: "$state-info-border", position: 332, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-info-heading-bg", value: "$state-info-bg", position: 333, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-warning-text", value: "$state-warning-text", position: 334, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-warning-border", value: "$state-warning-border", position: 335, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-warning-heading-bg", value: "$state-warning-bg", position: 336, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-danger-text", value: "$state-danger-text", position: 337, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-danger-border", value: "$state-danger-border", position: 338, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$panel-danger-heading-bg", value: "$state-danger-bg", position: 339, category_id: 35, framework: "bootstrap", version: "3.3" },
      { name: "$thumbnail-padding", value: "4px", position: 340, category_id: 28, framework: "bootstrap", version: "3.3" },
      { name: "$thumbnail-bg", value: "$body-bg", position: 341, category_id: 28, framework: "bootstrap", version: "3.3" },
      { name: "$thumbnail-border", value: "#ddd", position: 342, category_id: 28, framework: "bootstrap", version: "3.3" },
      { name: "$thumbnail-border-radius", value: "$border-radius-base", position: 343, category_id: 28, framework: "bootstrap", version: "3.3" },
      { name: "$thumbnail-caption-color", value: "$text-color", position: 344, category_id: 28, framework: "bootstrap", version: "3.3" },
      { name: "$thumbnail-caption-padding", value: "9px", position: 345, category_id: 28, framework: "bootstrap", version: "3.3" },
      { name: "$well-bg", value: "#f5f5f5", position: 346, category_id: 36, framework: "bootstrap", version: "3.3" },
      { name: "$well-border", value: "darken($well-bg, 7%)", position: 347, category_id: 36, framework: "bootstrap", version: "3.3" },
      { name: "$badge-color", value: "#fff", position: 348, category_id: 37, framework: "bootstrap", version: "3.3" },
      { name: "$badge-link-hover-color", value: "#fff", position: 349, category_id: 37, framework: "bootstrap", version: "3.3" },
      { name: "$badge-bg", value: "$gray-light", position: 350, category_id: 37, framework: "bootstrap", version: "3.3" },
      { name: "$badge-active-color", value: "$link-color", position: 351, category_id: 37, framework: "bootstrap", version: "3.3" },
      { name: "$badge-active-bg", value: "#fff", position: 352, category_id: 37, framework: "bootstrap", version: "3.3" },
      { name: "$badge-font-weight", value: "bold", position: 353, category_id: 37, framework: "bootstrap", version: "3.3" },
      { name: "$badge-line-height", value: "1", position: 354, category_id: 37, framework: "bootstrap", version: "3.3" },
      { name: "$badge-border-radius", value: "10px", position: 355, category_id: 37, framework: "bootstrap", version: "3.3" },
      { name: "$breadcrumb-padding-vertical", value: "8px", position: 356, category_id: 29, framework: "bootstrap", version: "3.3" },
      { name: "$breadcrumb-padding-horizontal", value: "15px", position: 357, category_id: 29, framework: "bootstrap", version: "3.3" },
      { name: "$breadcrumb-bg", value: "#f5f5f5", position: 358, category_id: 29, framework: "bootstrap", version: "3.3" },
      { name: "$breadcrumb-color", value: "#ccc", position: 359, category_id: 29, framework: "bootstrap", version: "3.3" },
      { name: "$breadcrumb-active-color", value: "$gray-light", position: 360, category_id: 29, framework: "bootstrap", version: "3.3" },
      { name: "$breadcrumb-separator", value: "\"/\"", position: 361, category_id: 29, framework: "bootstrap", version: "3.3" },
      { name: "$carousel-text-shadow", value: "0 1px 2px rgba(0,0,0,.6)", position: 362, category_id: 30, framework: "bootstrap", version: "3.3" },
      { name: "$carousel-control-color", value: "#fff", position: 363, category_id: 30, framework: "bootstrap", version: "3.3" },
      { name: "$carousel-control-width", value: "0.15", position: 364, category_id: 30, framework: "bootstrap", version: "3.3" },
      { name: "$carousel-control-opacity", value: "0.5", position: 365, category_id: 30, framework: "bootstrap", version: "3.3" },
      { name: "$carousel-control-font-size", value: "20px", position: 366, category_id: 30, framework: "bootstrap", version: "3.3" },
      { name: "$carousel-indicator-active-bg", value: "#fff", position: 367, category_id: 30, framework: "bootstrap", version: "3.3" },
      { name: "$carousel-indicator-border-color", value: "#fff", position: 368, category_id: 30, framework: "bootstrap", version: "3.3" },
      { name: "$carousel-caption-color", value: "#fff", position: 369, category_id: 30, framework: "bootstrap", version: "3.3" },
      { name: "$close-font-weight", value: "bold", position: 370, category_id: 31, framework: "bootstrap", version: "3.3" },
      { name: "$close-color", value: "#000", position: 371, category_id: 31, framework: "bootstrap", version: "3.3" },
      { name: "$close-text-shadow", value: "0 1px 0 #fff", position: 372, category_id: 31, framework: "bootstrap", version: "3.3" },
      { name: "$code-color", value: "#c7254e", position: 373, category_id: 32, framework: "bootstrap", version: "3.3" },
      { name: "$code-bg", value: "#f9f2f4", position: 374, category_id: 32, framework: "bootstrap", version: "3.3" },
      { name: "$kbd-color", value: "#fff", position: 375, category_id: 32, framework: "bootstrap", version: "3.3" },
      { name: "$kbd-bg", value: "#333", position: 376, category_id: 32, framework: "bootstrap", version: "3.3" },
      { name: "$pre-bg", value: "#f5f5f5", position: 377, category_id: 32, framework: "bootstrap", version: "3.3" },
      { name: "$pre-color", value: "$gray-dark", position: 378, category_id: 32, framework: "bootstrap", version: "3.3" },
      { name: "$pre-border-color", value: "#ccc", position: 379, category_id: 32, framework: "bootstrap", version: "3.3" },
      { name: "$pre-scrollable-max-height", value: "340px", position: 380, category_id: 32, framework: "bootstrap", version: "3.3" }
    ])
  end
end
