# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create({{ name: 'Star Wars' }, { name: 'Lord of the Rings' }})
#   Character.create(name: 'Luke', movie: movies.first)

Account.delete_all
@account = Account.create(name: "Demo Account", site_url: "www.example.com")

User.delete_all
@user = User.create(email: "demo@example.com", password: "test1234", password_confirmation: "test1234", account: @account)

Category.delete_all
Category.create([
  { id: 1, name: "Custom" },
  { id: 2, name: "Colors" },
  { id: 3, name: "Options" },
  { id: 4, name: "Spacing" },
  { id: 5, name: "Body" },
  { id: 6, name: "Links" },
  { id: 7, name: "Grid" },
  { id: 8, name: "Typography" },
  { id: 9, name: "Components" },
  { id: 10, name: "Tables" },
  { id: 11, name: "Buttons" },
  { id: 12, name: "Forms" },
  { id: 13, name: "Dropdowns" },
  { id: 14, name: "Navbar" },
  { id: 15, name: "Navs" },
  { id: 16, name: "Pagination" },
  { id: 17, name: "Pager" },
  { id: 18, name: "Jumbotron" },
  { id: 19, name: "From States And Alerts" },
  { id: 20, name: "Cards" },
  { id: 21, name: "Tooltips" },
  { id: 22, name: "Popovers" },
  { id: 23, name: "Labels" },
  { id: 24, name: "Modals" },
  { id: 25, name: "Alerts" },
  { id: 26, name: "Progress Bars" },
  { id: 27, name: "List Group" },
  { id: 28, name: "Image Thumbnails"},
  { id: 29, name: "Breadcrumbs" },
  { id: 30, name: "Carousel" },
  { id: 31, name: "Close" },
  { id: 32, name: "Code" },
  { id: 33, name: "Tabs" },
  { id: 34, name: "Pills" },
  { id: 35, name: "Panels" },
  { id: 36, name: "Wells" },
  { id: 37, name: "Badges" }
])




DefaultVariable.delete_all
DefaultVariable.create([
{name: "$gray-dark", value: "#373a3c", position: 1, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$gray", value: "#55595c", position: 2, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$gray-light", value: "#818a91", position: 3, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$gray-lighter", value: "#eceeef", position: 4, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$gray-lightest", value: "#f7f7f9", position: 5, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$brand-primary", value: "#0275d8", position: 6, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$brand-success", value: "#5cb85c", position: 7, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$brand-info", value: "#5bc0de", position: 8, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$brand-warning", value: "#f0ad4e", position: 9, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$brand-danger", value: "#d9534f", position: 10, category_id: 2, framework: "bootstrap", version: "4-alpha-2"},
{name: "$enable-flex", value: "false ", position: 11, category_id: 3, framework: "bootstrap", version: "4-alpha-2"},
{name: "$enable-rounded", value: "true ", position: 12, category_id: 3, framework: "bootstrap", version: "4-alpha-2"},
{name: "$enable-shadows", value: "false ", position: 13, category_id: 3, framework: "bootstrap", version: "4-alpha-2"},
{name: "$enable-gradients", value: "false ", position: 14, category_id: 3, framework: "bootstrap", version: "4-alpha-2"},
{name: "$enable-transitions", value: "false ", position: 15, category_id: 3, framework: "bootstrap", version: "4-alpha-2"},
{name: "$enable-hover-media-query", value: "false ", position: 16, category_id: 3, framework: "bootstrap", version: "4-alpha-2"},
{name: "$enable-grid-classes", value: "true ", position: 17, category_id: 3, framework: "bootstrap", version: "4-alpha-2"},
{name: "$spacer", value: "1rem", position: 18, category_id: 4, framework: "bootstrap", version: "4-alpha-2"},
{name: "$spacer-x", value: "$spacer", position: 19, category_id: 4, framework: "bootstrap", version: "4-alpha-2"},
{name: "$spacer-y", value: "$spacer", position: 20, category_id: 4, framework: "bootstrap", version: "4-alpha-2"},
{name: "$border-width", value: "1px", position: 21, category_id: 4, framework: "bootstrap", version: "4-alpha-2"},
{name: "$body-bg", value: "#fff", position: 22, category_id: 5, framework: "bootstrap", version: "4-alpha-2"},
{name: "$body-color", value: "$gray-dark", position: 23, category_id: 5, framework: "bootstrap", version: "4-alpha-2"},
{name: "$link-color", value: "$brand-primary", position: 24, category_id: 6, framework: "bootstrap", version: "4-alpha-2"},
{name: "$link-decoration", value: "none", position: 25, category_id: 6, framework: "bootstrap", version: "4-alpha-2"},
{name: "$link-hover-color", value: "darken($link-color, 15%)", position: 26, category_id: 6, framework: "bootstrap", version: "4-alpha-2"},
{name: "$link-hover-decoration", value: "underline", position: 27, category_id: 6, framework: "bootstrap", version: "4-alpha-2"},
{name: "$grid-columns", value: "12", position: 28, category_id: 7, framework: "bootstrap", version: "4-alpha-2"},
{name: "$grid-gutter-width", value: "1.875rem // 30px", position: 29, category_id: 7, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-family-sans-serif", value: "Helvetica Neue, Helvetica, Arial, sans-serif", position: 30, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-family-serif", value: "Georgia, \"Times New Roman\", Times, serif", position: 31, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-family-monospace", value: "Menlo, Monaco, Consolas, \"Courier New\", monospace", position: 32, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-family-base", value: "$font-family-sans-serif", position: 33, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-root", value: "16px", position: 34, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-base", value: "1rem", position: 35, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-lg", value: "1.25rem", position: 36, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-sm", value: ".875rem", position: 37, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-xs", value: ".75rem", position: 38, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-h1", value: "2.5rem", position: 39, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-h2", value: "2rem", position: 40, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-h3", value: "1.75rem", position: 41, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-h4", value: "1.5rem", position: 42, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-h5", value: "1.25rem", position: 43, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$font-size-h6", value: "1rem", position: 44, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$display1-size", value: "6rem", position: 45, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$display2-size", value: "5.5rem", position: 46, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$display3-size", value: "4.5rem", position: 47, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$display4-size", value: "3.5rem", position: 48, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$display1-weight", value: "300", position: 49, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$display2-weight", value: "300", position: 50, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$display3-weight", value: "300", position: 51, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$display4-weight", value: "300", position: 52, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$line-height", value: "1.5", position: 53, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$headings-margin-bottom", value: "($spacer / 2)", position: 54, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$headings-font-family", value: "inherit", position: 55, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$headings-font-weight", value: "500", position: 56, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$headings-line-height", value: "1.1", position: 57, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$headings-color", value: "inherit", position: 58, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$lead-font-size", value: "1.25rem", position: 59, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$lead-font-weight", value: "300", position: 60, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$text-muted", value: "$gray-light", position: 61, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$abbr-border-color", value: "$gray-light", position: 62, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$blockquote-small-color", value: "$gray-light", position: 63, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$blockquote-font-size", value: "($font-size-base * 1.25)", position: 64, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$blockquote-border-color", value: "$gray-lighter", position: 65, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$hr-border-color", value: "rgba(0,0,0,.1)", position: 66, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$hr-border-width", value: "$border-width", position: 67, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dt-font-weight", value: "bold", position: 68, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nested-kbd-font-weight", value: "bold", position: 69, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-inline-padding", value: "5px", position: 70, category_id: 8, framework: "bootstrap", version: "4-alpha-2"},
{name: "$line-height-lg", value: "(4 / 3)", position: 71, category_id: 9, framework: "bootstrap", version: "4-alpha-2"},
{name: "$line-height-sm", value: "1.5", position: 72, category_id: 9, framework: "bootstrap", version: "4-alpha-2"},
{name: "$border-radius", value: ".25rem", position: 73, category_id: 9, framework: "bootstrap", version: "4-alpha-2"},
{name: "$border-radius-lg", value: ".3rem", position: 74, category_id: 9, framework: "bootstrap", version: "4-alpha-2"},
{name: "$border-radius-sm", value: ".2rem", position: 75, category_id: 9, framework: "bootstrap", version: "4-alpha-2"},
{name: "$component-active-color", value: "#fff", position: 76, category_id: 9, framework: "bootstrap", version: "4-alpha-2"},
{name: "$component-active-bg", value: "$brand-primary", position: 77, category_id: 9, framework: "bootstrap", version: "4-alpha-2"},
{name: "$caret-width", value: ".3em", position: 78, category_id: 9, framework: "bootstrap", version: "4-alpha-2"},
{name: "$caret-width-lg", value: "$caret-width", position: 79, category_id: 9, framework: "bootstrap", version: "4-alpha-2"},
{name: "$table-cell-padding", value: ".75rem", position: 80, category_id: 10, framework: "bootstrap", version: "4-alpha-2"},
{name: "$table-sm-cell-padding", value: ".3rem", position: 81, category_id: 10, framework: "bootstrap", version: "4-alpha-2"},
{name: "$table-bg", value: "transparent", position: 82, category_id: 10, framework: "bootstrap", version: "4-alpha-2"},
{name: "$table-bg-accent", value: "#f9f9f9", position: 83, category_id: 10, framework: "bootstrap", version: "4-alpha-2"},
{name: "$table-bg-hover", value: "#f5f5f5", position: 84, category_id: 10, framework: "bootstrap", version: "4-alpha-2"},
{name: "$table-bg-active", value: "$table-bg-hover", position: 85, category_id: 10, framework: "bootstrap", version: "4-alpha-2"},
{name: "$table-border-width", value: "$border-width", position: 86, category_id: 10, framework: "bootstrap", version: "4-alpha-2"},
{name: "$table-border-color", value: "$gray-lighter", position: 87, category_id: 10, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-padding-x", value: "1rem", position: 88, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-padding-y", value: ".375rem", position: 89, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-font-weight", value: "normal", position: 90, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-primary-color", value: "#fff", position: 91, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-primary-bg", value: "$brand-primary", position: 92, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-primary-border", value: "$btn-primary-bg", position: 93, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-secondary-color", value: "$gray-dark", position: 94, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-secondary-bg", value: "#fff", position: 95, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-secondary-border", value: "#ccc", position: 96, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-info-color", value: "#fff", position: 97, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-info-bg", value: "$brand-info", position: 98, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-info-border", value: "$btn-info-bg", position: 99, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-success-color", value: "#fff", position: 100, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-success-bg", value: "$brand-success", position: 101, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-success-border", value: "$btn-success-bg", position: 102, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-warning-color", value: "#fff", position: 103, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-warning-bg", value: "$brand-warning", position: 104, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-warning-border", value: "$btn-warning-bg", position: 105, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-danger-color", value: "#fff", position: 106, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-danger-bg", value: "$brand-danger", position: 107, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-danger-border", value: "$btn-danger-bg", position: 108, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-link-disabled-color", value: "$gray-light", position: 109, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-padding-x-sm", value: ".75rem", position: 110, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-padding-y-sm", value: ".25rem", position: 111, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-padding-x-lg", value: "1.25rem", position: 112, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-padding-y-lg", value: ".75rem", position: 113, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-border-radius", value: "$border-radius", position: 114, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-border-radius-lg", value: "$border-radius-lg", position: 115, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$btn-border-radius-sm", value: "$border-radius-sm", position: 116, category_id: 11, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-padding-x", value: ".75rem", position: 117, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-padding-y", value: ".375rem", position: 118, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-bg", value: "#fff", position: 119, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-bg-disabled", value: "$gray-lighter", position: 120, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-color", value: "$gray", position: 121, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-border-color", value: "#ccc", position: 122, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-btn-border-width", value: "$border-width // For form controls and buttons", position: 123, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-box-shadow", value: "inset 0 1px 1px rgba(0,0,0,.075)", position: 124, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-border-radius", value: "$border-radius", position: 125, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-border-radius-lg", value: "$border-radius-lg", position: 126, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-border-radius-sm", value: "$border-radius-sm", position: 127, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-border-focus", value: "#66afe9", position: 128, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-box-shadow-focus", value: "rgba(102,175,233,.6)", position: 129, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-color-placeholder", value: "#999", position: 130, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-padding-x-sm", value: ".75rem", position: 131, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-padding-y-sm", value: ".275rem", position: 132, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-padding-x-lg", value: "1.25rem", position: 133, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-padding-y-lg", value: ".75rem", position: 134, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-height", value: "(($font-size-base * $line-height) + ($input-padding-y * 2))", position: 135, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-height-lg", value: "(($font-size-lg * $line-height-lg) + ($input-padding-y-lg * 2))", position: 136, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-height-sm", value: "(($font-size-sm * $line-height-sm) + ($input-padding-y-sm * 2))", position: 137, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$form-group-margin-bottom", value: "$spacer-y", position: 138, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-group-addon-bg", value: "$gray-lighter", position: 139, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$input-group-addon-border-color", value: "$input-border-color", position: 140, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$cursor-disabled", value: "not-allowed", position: 141, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$form-icon-success", value: "\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MTIgNzkyIj48cGF0aCBmaWxsPSIjNWNiODVjIiBkPSJNMjMzLjggNjEwYy0xMy4zIDAtMjYtNi0zNC0xNi44TDkwLjUgNDQ4LjhDNzYuMyA0MzAgODAgNDAzLjMgOTguOCAzODljMTguOC0xNC4yIDQ1LjUtMTAuNCA1OS44IDguNGw3MiA5NUw0NTEuMyAyNDJjMTIuNS0yMCAzOC44LTI2LjIgNTguOC0xMy43IDIwIDEyLjQgMjYgMzguNyAxMy43IDU4LjhMMjcwIDU5MGMtNy40IDEyLTIwLjIgMTkuNC0zNC4zIDIwaC0yeiIvPjwvc3ZnPg==\"", position: 142, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$form-icon-warning", value: "\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MTIgNzkyIj48cGF0aCBmaWxsPSIjZjBhZDRlIiBkPSJNNjAzIDY0MC4ybC0yNzguNS01MDljLTMuOC02LjYtMTAuOC0xMC42LTE4LjUtMTAuNnMtMTQuNyA0LTE4LjUgMTAuNkw5IDY0MC4yYy0zLjcgNi41LTMuNiAxNC40LjIgMjAuOCAzLjggNi41IDEwLjggMTAuNCAxOC4zIDEwLjRoNTU3YzcuNiAwIDE0LjYtNCAxOC40LTEwLjQgMy41LTYuNCAzLjYtMTQuNCAwLTIwLjh6bS0yNjYuNC0zMGgtNjEuMlY1NDloNjEuMnY2MS4yem0wLTEwN2gtNjEuMlYzMDRoNjEuMnYxOTl6Ii8+PC9zdmc+\"", position: 143, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$form-icon-danger", value: "\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MTIgNzkyIj48cGF0aCBmaWxsPSIjZDk1MzRmIiBkPSJNNDQ3IDU0NC40Yy0xNC40IDE0LjQtMzcuNiAxNC40LTUyIDBsLTg5LTkyLjctODkgOTIuN2MtMTQuNSAxNC40LTM3LjcgMTQuNC01MiAwLTE0LjQtMTQuNC0xNC40LTM3LjYgMC01Mmw5Mi40LTk2LjMtOTIuNC05Ni4zYy0xNC40LTE0LjQtMTQuNC0zNy42IDAtNTJzMzcuNi0xNC4zIDUyIDBsODkgOTIuOCA4OS4yLTkyLjdjMTQuNC0xNC40IDM3LjYtMTQuNCA1MiAwIDE0LjMgMTQuNCAxNC4zIDM3LjYgMCA1MkwzNTQuNiAzOTZsOTIuNCA5Ni40YzE0LjQgMTQuNCAxNC40IDM3LjYgMCA1MnoiLz48L3N2Zz4=\"", position: 144, category_id: 12, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-bg", value: "#fff", position: 145, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-border-color", value: "rgba(0,0,0,.15)", position: 146, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-border-width", value: "$border-width", position: 147, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-divider-bg", value: "#e5e5e5", position: 148, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-link-color", value: "$gray-dark", position: 149, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-link-hover-color", value: "darken($gray-dark, 5%)", position: 150, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-link-hover-bg", value: "#f5f5f5", position: 151, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-link-active-color", value: "$component-active-color", position: 152, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-link-active-bg", value: "$component-active-bg", position: 153, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-link-disabled-color", value: "$gray-light", position: 154, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$dropdown-header-color", value: "$gray-light", position: 155, category_id: 13, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-border-radius", value: "$border-radius", position: 156, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-padding-horizontal", value: "$spacer", position: 157, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-padding-vertical", value: "($spacer / 2)", position: 158, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-dark-color", value: "rgba(255,255,255,.5)", position: 159, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-dark-hover-color", value: "rgba(255,255,255,.75)", position: 160, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-dark-active-color", value: "rgba(255,255,255,1)", position: 161, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-dark-disabled-color", value: "rgba(255,255,255,.25)", position: 162, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-light-color", value: "rgba(0,0,0,.3)", position: 163, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-light-hover-color", value: "rgba(0,0,0,.6)", position: 164, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-light-active-color", value: "rgba(0,0,0,.8)", position: 165, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$navbar-light-disabled-color", value: "rgba(0,0,0,.15)", position: 166, category_id: 14, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-link-padding", value: ".5em 1em", position: 167, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-link-hover-bg", value: "$gray-lighter", position: 168, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-disabled-link-color", value: "$gray-light", position: 169, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-disabled-link-hover-color", value: "$gray-light", position: 170, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-tabs-border-color", value: "#ddd", position: 171, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-tabs-link-border-width", value: "$border-width", position: 172, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-tabs-link-hover-border-color", value: "$gray-lighter", position: 173, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-tabs-active-link-hover-bg", value: "$body-bg", position: 174, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-tabs-active-link-hover-color", value: "$gray", position: 175, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-tabs-active-link-hover-border-color", value: "#ddd", position: 176, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-tabs-justified-link-border-color", value: "#ddd", position: 177, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-tabs-justified-active-link-border-color", value: "$body-bg", position: 178, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-pills-border-radius", value: "$border-radius", position: 179, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-pills-active-link-hover-bg", value: "$component-active-bg", position: 180, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$nav-pills-active-link-hover-color", value: "$component-active-color", position: 181, category_id: 15, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-padding-x", value: ".75rem", position: 182, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-padding-y", value: ".5rem", position: 183, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-padding-x-sm", value: ".75rem", position: 184, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-padding-y-sm", value: ".275rem", position: 185, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-padding-x-lg", value: "1.5rem", position: 186, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-padding-y-lg", value: ".75rem", position: 187, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-color", value: "$link-color", position: 188, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-bg", value: "#fff", position: 189, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-border-width", value: "$border-width", position: 190, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-border-color", value: "#ddd", position: 191, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-hover-color", value: "$link-hover-color", position: 192, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-hover-bg", value: "$gray-lighter", position: 193, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-hover-border", value: "#ddd", position: 194, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-active-color", value: "#fff", position: 195, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-active-bg", value: "$brand-primary", position: 196, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-active-border", value: "$brand-primary", position: 197, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-disabled-color", value: "$gray-light", position: 198, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-disabled-bg", value: "#fff", position: 199, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pagination-disabled-border", value: "#ddd", position: 200, category_id: 16, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pager-bg", value: "$pagination-bg", position: 201, category_id: 17, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pager-border-width", value: "$border-width", position: 202, category_id: 17, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pager-border-color", value: "$pagination-border-color", position: 203, category_id: 17, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pager-border-radius", value: "15px", position: 204, category_id: 17, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pager-hover-bg", value: "$pagination-hover-bg", position: 205, category_id: 17, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pager-active-bg", value: "$pagination-active-bg", position: 206, category_id: 17, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pager-active-color", value: "$pagination-active-color", position: 207, category_id: 17, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pager-disabled-color", value: "$pagination-disabled-color", position: 208, category_id: 17, framework: "bootstrap", version: "4-alpha-2"},
{name: "$jumbotron-padding", value: "2rem", position: 209, category_id: 18, framework: "bootstrap", version: "4-alpha-2"},
{name: "$jumbotron-bg", value: "$gray-lighter", position: 210, category_id: 18, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-success-text", value: "#3c763d", position: 211, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-success-bg", value: "#dff0d8", position: 212, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-success-border", value: "darken($state-success-bg, 5%)", position: 213, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-info-text", value: "#31708f", position: 214, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-info-bg", value: "#d9edf7", position: 215, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-info-border", value: "darken($state-info-bg, 7%)", position: 216, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-warning-text", value: "#8a6d3b", position: 217, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-warning-bg", value: "#fcf8e3", position: 218, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-warning-border", value: "darken($state-warning-bg, 5%)", position: 219, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-danger-text", value: "#a94442", position: 220, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-danger-bg", value: "#f2dede", position: 221, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$state-danger-border", value: "darken($state-danger-bg, 5%)", position: 222, category_id: 19, framework: "bootstrap", version: "4-alpha-2"},
{name: "$card-spacer-x", value: "1.25rem", position: 223, category_id: 20, framework: "bootstrap", version: "4-alpha-2"},
{name: "$card-spacer-y", value: ".75rem", position: 224, category_id: 20, framework: "bootstrap", version: "4-alpha-2"},
{name: "$card-border-width", value: "1px", position: 225, category_id: 20, framework: "bootstrap", version: "4-alpha-2"},
{name: "$card-border-radius", value: "$border-radius", position: 226, category_id: 20, framework: "bootstrap", version: "4-alpha-2"},
{name: "$card-border-color", value: "#e5e5e5", position: 227, category_id: 20, framework: "bootstrap", version: "4-alpha-2"},
{name: "$card-border-radius-inner", value: "$card-border-radius", position: 228, category_id: 20, framework: "bootstrap", version: "4-alpha-2"},
{name: "$card-cap-bg", value: "#f5f5f5", position: 229, category_id: 20, framework: "bootstrap", version: "4-alpha-2"},
{name: "$card-bg", value: "#fff", position: 230, category_id: 20, framework: "bootstrap", version: "4-alpha-2"},
{name: "$card-link-hover-color", value: "#fff", position: 231, category_id: 20, framework: "bootstrap", version: "4-alpha-2"},
{name: "$tooltip-max-width", value: "200px", position: 232, category_id: 21, framework: "bootstrap", version: "4-alpha-2"},
{name: "$tooltip-color", value: "#fff", position: 233, category_id: 21, framework: "bootstrap", version: "4-alpha-2"},
{name: "$tooltip-bg", value: "#000", position: 234, category_id: 21, framework: "bootstrap", version: "4-alpha-2"},
{name: "$tooltip-opacity", value: "0.9", position: 235, category_id: 21, framework: "bootstrap", version: "4-alpha-2"},
{name: "$tooltip-arrow-width", value: "5px", position: 236, category_id: 21, framework: "bootstrap", version: "4-alpha-2"},
{name: "$tooltip-arrow-color", value: "$tooltip-bg", position: 237, category_id: 21, framework: "bootstrap", version: "4-alpha-2"},
{name: "$popover-bg", value: "#fff", position: 238, category_id: 22, framework: "bootstrap", version: "4-alpha-2"},
{name: "$popover-max-width", value: "276px", position: 239, category_id: 22, framework: "bootstrap", version: "4-alpha-2"},
{name: "$popover-border-width", value: "$border-width", position: 240, category_id: 22, framework: "bootstrap", version: "4-alpha-2"},
{name: "$popover-border-color", value: "rgba(0,0,0,.2)", position: 241, category_id: 22, framework: "bootstrap", version: "4-alpha-2"},
{name: "$popover-title-bg", value: "darken($popover-bg, 3%)", position: 242, category_id: 22, framework: "bootstrap", version: "4-alpha-2"},
{name: "$popover-arrow-width", value: "10px", position: 243, category_id: 22, framework: "bootstrap", version: "4-alpha-2"},
{name: "$popover-arrow-color", value: "$popover-bg", position: 244, category_id: 22, framework: "bootstrap", version: "4-alpha-2"},
{name: "$popover-arrow-outer-width", value: "($popover-arrow-width + 1)", position: 245, category_id: 22, framework: "bootstrap", version: "4-alpha-2"},
{name: "$popover-arrow-outer-color", value: "fade-in($popover-border-color, 0.05)", position: 246, category_id: 22, framework: "bootstrap", version: "4-alpha-2"},
{name: "$label-default-bg", value: "$gray-light", position: 247, category_id: 23, framework: "bootstrap", version: "4-alpha-2"},
{name: "$label-primary-bg", value: "$brand-primary", position: 248, category_id: 23, framework: "bootstrap", version: "4-alpha-2"},
{name: "$label-success-bg", value: "$brand-success", position: 249, category_id: 23, framework: "bootstrap", version: "4-alpha-2"},
{name: "$label-info-bg", value: "$brand-info", position: 250, category_id: 23, framework: "bootstrap", version: "4-alpha-2"},
{name: "$label-warning-bg", value: "$brand-warning", position: 251, category_id: 23, framework: "bootstrap", version: "4-alpha-2"},
{name: "$label-danger-bg", value: "$brand-danger", position: 252, category_id: 23, framework: "bootstrap", version: "4-alpha-2"},
{name: "$label-color", value: "#fff", position: 253, category_id: 23, framework: "bootstrap", version: "4-alpha-2"},
{name: "$label-link-hover-color", value: "#fff", position: 254, category_id: 23, framework: "bootstrap", version: "4-alpha-2"},
{name: "$label-font-weight", value: "bold", position: 255, category_id: 23, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-inner-padding", value: "15px", position: 256, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-title-padding", value: "15px", position: 257, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-title-line-height", value: "$line-height", position: 258, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-content-bg", value: "#fff", position: 259, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-content-border-color", value: "rgba(0,0,0,.2)", position: 260, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-backdrop-bg", value: "#000", position: 261, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-backdrop-opacity", value: "0.5", position: 262, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-header-border-color", value: "#e5e5e5", position: 263, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-footer-border-color", value: "$modal-header-border-color", position: 264, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-lg", value: "900px", position: 265, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-md", value: "600px", position: 266, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$modal-sm", value: "300px", position: 267, category_id: 24, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-padding", value: "15px", position: 268, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-border-radius", value: "$border-radius", position: 269, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-link-font-weight", value: "bold", position: 270, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-border-width", value: "$border-width", position: 271, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-success-bg", value: "$state-success-bg", position: 272, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-success-text", value: "$state-success-text", position: 273, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-success-border", value: "$state-success-border", position: 274, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-info-bg", value: "$state-info-bg", position: 275, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-info-text", value: "$state-info-text", position: 276, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-info-border", value: "$state-info-border", position: 277, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-warning-bg", value: "$state-warning-bg", position: 278, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-warning-text", value: "$state-warning-text", position: 279, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-warning-border", value: "$state-warning-border", position: 280, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-danger-bg", value: "$state-danger-bg", position: 281, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-danger-text", value: "$state-danger-text", position: 282, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$alert-danger-border", value: "$state-danger-border", position: 283, category_id: 25, framework: "bootstrap", version: "4-alpha-2"},
{name: "$progress-bg", value: "#f5f5f5", position: 284, category_id: 26, framework: "bootstrap", version: "4-alpha-2"},
{name: "$progress-bar-color", value: "#fff", position: 285, category_id: 26, framework: "bootstrap", version: "4-alpha-2"},
{name: "$progress-border-radius", value: "$border-radius", position: 286, category_id: 26, framework: "bootstrap", version: "4-alpha-2"},
{name: "$progress-bar-bg", value: "$brand-primary", position: 287, category_id: 26, framework: "bootstrap", version: "4-alpha-2"},
{name: "$progress-bar-success-bg", value: "$brand-success", position: 288, category_id: 26, framework: "bootstrap", version: "4-alpha-2"},
{name: "$progress-bar-warning-bg", value: "$brand-warning", position: 289, category_id: 26, framework: "bootstrap", version: "4-alpha-2"},
{name: "$progress-bar-danger-bg", value: "$brand-danger", position: 290, category_id: 26, framework: "bootstrap", version: "4-alpha-2"},
{name: "$progress-bar-info-bg", value: "$brand-info", position: 291, category_id: 26, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-bg", value: "#fff", position: 292, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-border-color", value: "#ddd", position: 293, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-border-width", value: "$border-width", position: 294, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-border-radius", value: "$border-radius", position: 295, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-hover-bg", value: "#f5f5f5", position: 296, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-active-color", value: "$component-active-color", position: 297, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-active-bg", value: "$component-active-bg", position: 298, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-active-border", value: "$list-group-active-bg", position: 299, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-active-text-color", value: "lighten($list-group-active-bg, 40%)", position: 300, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-disabled-color", value: "$gray-light", position: 301, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-disabled-bg", value: "$gray-lighter", position: 302, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-disabled-text-color", value: "$list-group-disabled-color", position: 303, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-link-color", value: "#555", position: 304, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-link-hover-color", value: "$list-group-link-color", position: 305, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$list-group-link-heading-color", value: "#333", position: 306, category_id: 27, framework: "bootstrap", version: "4-alpha-2"},
{name: "$thumbnail-padding", value: ".25rem", position: 307, category_id: 28, framework: "bootstrap", version: "4-alpha-2"},
{name: "$thumbnail-bg", value: "$body-bg", position: 308, category_id: 28, framework: "bootstrap", version: "4-alpha-2"},
{name: "$thumbnail-border-width", value: "$border-width", position: 309, category_id: 28, framework: "bootstrap", version: "4-alpha-2"},
{name: "$thumbnail-border-color", value: "#ddd", position: 310, category_id: 28, framework: "bootstrap", version: "4-alpha-2"},
{name: "$thumbnail-border-radius", value: "$border-radius", position: 311, category_id: 28, framework: "bootstrap", version: "4-alpha-2"},
{name: "$breadcrumb-padding-vertical", value: ".75rem", position: 312, category_id: 29, framework: "bootstrap", version: "4-alpha-2"},
{name: "$breadcrumb-padding-horizontal", value: "1rem", position: 313, category_id: 29, framework: "bootstrap", version: "4-alpha-2"},
{name: "$breadcrumb-bg", value: "$gray-lighter", position: 314, category_id: 29, framework: "bootstrap", version: "4-alpha-2"},
{name: "$breadcrumb-divider-color", value: "$gray-light", position: 315, category_id: 29, framework: "bootstrap", version: "4-alpha-2"},
{name: "$breadcrumb-active-color", value: "$gray-light", position: 316, category_id: 29, framework: "bootstrap", version: "4-alpha-2"},
{name: "$breadcrumb-divider", value: "\"/\"", position: 317, category_id: 29, framework: "bootstrap", version: "4-alpha-2"},
{name: "$carousel-text-shadow", value: "0 1px 2px rgba(0,0,0,.6)", position: 318, category_id: 30, framework: "bootstrap", version: "4-alpha-2"},
{name: "$carousel-control-color", value: "#fff", position: 319, category_id: 30, framework: "bootstrap", version: "4-alpha-2"},
{name: "$carousel-control-width", value: "0.15", position: 320, category_id: 30, framework: "bootstrap", version: "4-alpha-2"},
{name: "$carousel-control-opacity", value: "0.5", position: 321, category_id: 30, framework: "bootstrap", version: "4-alpha-2"},
{name: "$carousel-control-font-size", value: "20px", position: 322, category_id: 30, framework: "bootstrap", version: "4-alpha-2"},
{name: "$carousel-indicator-active-bg", value: "#fff", position: 323, category_id: 30, framework: "bootstrap", version: "4-alpha-2"},
{name: "$carousel-indicator-border-color", value: "#fff", position: 324, category_id: 30, framework: "bootstrap", version: "4-alpha-2"},
{name: "$carousel-caption-color", value: "#fff", position: 325, category_id: 30, framework: "bootstrap", version: "4-alpha-2"},
{name: "$close-font-weight", value: "bold", position: 326, category_id: 31, framework: "bootstrap", version: "4-alpha-2"},
{name: "$close-color", value: "#000", position: 327, category_id: 31, framework: "bootstrap", version: "4-alpha-2"},
{name: "$close-text-shadow", value: "0 1px 0 #fff", position: 328, category_id: 31, framework: "bootstrap", version: "4-alpha-2"},
{name: "$code-color", value: "#bd4147", position: 329, category_id: 32, framework: "bootstrap", version: "4-alpha-2"},
{name: "$code-bg", value: "#f7f7f9", position: 330, category_id: 32, framework: "bootstrap", version: "4-alpha-2"},
{name: "$kbd-color", value: "#fff", position: 331, category_id: 32, framework: "bootstrap", version: "4-alpha-2"},
{name: "$kbd-bg", value: "#333", position: 332, category_id: 32, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pre-bg", value: "#f7f7f9", position: 333, category_id: 32, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pre-color", value: "$gray-dark", position: 334, category_id: 32, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pre-border-color", value: "#ccc", position: 335, category_id: 32, framework: "bootstrap", version: "4-alpha-2"},
{name: "$pre-scrollable-max-height", value: "340px", position: 336, category_id: 32, framework: "bootstrap", version: "4-alpha-2"},

{name: "$body-bg", value: "#fff", position: 1, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$gray-base", value: "#000", position: 2, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$gray-darker", value: "lighten($gray-base, 13.5%)", position: 3, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$gray-dark", value: "lighten($gray-base, 20%)", position: 4, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$gray", value: "lighten($gray-base, 33.5%)", position: 5, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$gray-light", value: "lighten($gray-base, 46.7%)", position: 6, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$gray-lighter", value: "lighten($gray-base, 93.5%)", position: 7, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$brand-primary", value: "darken(#428bca, 6.5%)", position: 8, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$brand-success", value: "#5cb85c", position: 9, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$brand-info", value: "#5bc0de", position: 10, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$brand-warning", value: "#f0ad4e", position: 11, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$brand-danger", value: "#d9534f", position: 12, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$link-color", value: "$brand-primary", position: 13, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$link-hover-color", value: "darken($link-color, 15%)", position: 14, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$link-hover-decoration", value: "underline", position: 15, category_id: 2, framework: "bootstrap", version: "3.3"},
{name: "$text-color", value: "$gray-dark", position: 16, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-family-sans-serif", value: "\"Helvetica Neue\", Helvetica, Arial, sans-serif", position: 17, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-family-serif", value: "Georgia, \"Times New Roman\", Times, serif", position: 18, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-family-monospace", value: "Menlo, Monaco, Consolas, \"Courier New\", monospace", position: 19, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-family-base", value: "$font-family-sans-serif", position: 20, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-size-base", value: "14px", position: 21, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-size-large", value: "ceil(($font-size-base * 1.25))", position: 22, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-size-small", value: "ceil(($font-size-base * 0.85))", position: 23, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-size-h1", value: "floor(($font-size-base * 2.6))", position: 24, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-size-h2", value: "floor(($font-size-base * 2.15))", position: 25, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-size-h3", value: "ceil(($font-size-base * 1.7))", position: 26, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-size-h4", value: "ceil(($font-size-base * 1.25))", position: 27, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-size-h5", value: "$font-size-base", position: 28, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$font-size-h6", value: "ceil(($font-size-base * 0.85))", position: 29, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$line-height-base", value: "1.428571429", position: 30, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$line-height-computed", value: "floor(($font-size-base * $line-height-base))", position: 31, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$headings-font-family", value: "inherit", position: 32, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$headings-font-weight", value: "500", position: 33, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$headings-line-height", value: "1.1", position: 34, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$headings-color", value: "inherit", position: 35, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$component-offset-horizontal", value: "180px", position: 36, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$text-muted", value: "$gray-light", position: 37, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$abbr-border-color", value: "$gray-light", position: 38, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$headings-small-color", value: "$gray-light", position: 39, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$blockquote-small-color", value: "$gray-light", position: 40, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$blockquote-font-size", value: "($font-size-base * 1.25)", position: 41, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$blockquote-border-color", value: "$gray-lighter", position: 42, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$page-header-border-color", value: "$gray-lighter", position: 43, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$dl-horizontal-offset", value: "$component-offset-horizontal", position: 44, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$dl-horizontal-breakpoint", value: "$grid-float-breakpoint", position: 45, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$hr-border", value: "$gray-lighter", position: 46, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$icon-font-path", value: "if($bootstrap-sass-asset-helper, \"bootstrap/\", \"../fonts/bootstrap/\")", position: 47, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$icon-font-name", value: "\"glyphicons-halflings-regular\"", position: 48, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$icon-font-svg-id", value: "\"glyphicons_halflingsregular\"", position: 49, category_id: 8, framework: "bootstrap", version: "3.3"},
{name: "$padding-base-vertical", value: "6px", position: 50, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$padding-base-horizontal", value: "12px", position: 51, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$padding-large-vertical", value: "10px", position: 52, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$padding-large-horizontal", value: "16px", position: 53, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$padding-small-vertical", value: "5px", position: 54, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$padding-small-horizontal", value: "10px", position: 55, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$padding-xs-vertical", value: "1px", position: 56, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$padding-xs-horizontal", value: "5px", position: 57, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$line-height-large", value: "1.3333333", position: 58, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$line-height-small", value: "1.5", position: 59, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$border-radius-base", value: "4px", position: 60, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$border-radius-large", value: "6px", position: 61, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$border-radius-small", value: "3px", position: 62, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$component-active-color", value: "#fff", position: 63, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$component-active-bg", value: "$brand-primary", position: 64, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$caret-width-base", value: "4px", position: 65, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$caret-width-large", value: "5px", position: 66, category_id: 9, framework: "bootstrap", version: "3.3"},
{name: "$table-cell-padding", value: "8px", position: 67, category_id: 10, framework: "bootstrap", version: "3.3"},
{name: "$table-condensed-cell-padding", value: "5px", position: 68, category_id: 10, framework: "bootstrap", version: "3.3"},
{name: "$table-bg", value: "transparent", position: 69, category_id: 10, framework: "bootstrap", version: "3.3"},
{name: "$table-bg-accent", value: "#f9f9f9", position: 70, category_id: 10, framework: "bootstrap", version: "3.3"},
{name: "$table-bg-hover", value: "#f5f5f5", position: 71, category_id: 10, framework: "bootstrap", version: "3.3"},
{name: "$table-bg-active", value: "$table-bg-hover", position: 72, category_id: 10, framework: "bootstrap", version: "3.3"},
{name: "$table-border-color", value: "#ddd", position: 73, category_id: 10, framework: "bootstrap", version: "3.3"},
{name: "$btn-font-weight", value: "normal", position: 74, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-default-color", value: "#333", position: 75, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-default-bg", value: "#fff", position: 76, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-default-border", value: "#ccc", position: 77, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-primary-color", value: "#fff", position: 78, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-primary-bg", value: "$brand-primary", position: 79, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-primary-border", value: "darken($btn-primary-bg, 5%)", position: 80, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-success-color", value: "#fff", position: 81, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-success-bg", value: "$brand-success", position: 82, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-success-border", value: "darken($btn-success-bg, 5%)", position: 83, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-info-color", value: "#fff", position: 84, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-info-bg", value: "$brand-info", position: 85, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-info-border", value: "darken($btn-info-bg, 5%)", position: 86, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-warning-color", value: "#fff", position: 87, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-warning-bg", value: "$brand-warning", position: 88, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-warning-border", value: "darken($btn-warning-bg, 5%)", position: 89, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-danger-color", value: "#fff", position: 90, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-danger-bg", value: "$brand-danger", position: 91, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-danger-border", value: "darken($btn-danger-bg, 5%)", position: 92, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-link-disabled-color", value: "$gray-light", position: 93, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-border-radius-base", value: "$border-radius-base", position: 94, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-border-radius-large", value: "$border-radius-large", position: 95, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$btn-border-radius-small", value: "$border-radius-small", position: 96, category_id: 11, framework: "bootstrap", version: "3.3"},
{name: "$input-bg", value: "#fff", position: 97, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-bg-disabled", value: "$gray-lighter", position: 98, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-color", value: "$gray", position: 99, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-border", value: "#ccc", position: 100, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-border-radius", value: "$border-radius-base", position: 101, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-border-radius-large", value: "$border-radius-large", position: 102, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-border-radius-small", value: "$border-radius-small", position: 103, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-border-focus", value: "#66afe9", position: 104, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-color-placeholder", value: "#999", position: 105, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-height-base", value: "($line-height-computed + ($padding-base-vertical * 2) + 2)", position: 106, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-height-large", value: "(ceil($font-size-large * $line-height-large) + ($padding-large-vertical * 2) + 2)", position: 107, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-height-small", value: "(floor($font-size-small * $line-height-small) + ($padding-small-vertical * 2) + 2)", position: 108, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$form-group-margin-bottom", value: "15px", position: 109, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$legend-color", value: "$gray-dark", position: 110, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$legend-border-color", value: "#e5e5e5", position: 111, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-group-addon-bg", value: "$gray-lighter", position: 112, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$input-group-addon-border-color", value: "$input-border", position: 113, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$cursor-disabled", value: "not-allowed", position: 114, category_id: 12, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-bg", value: "#fff", position: 115, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-border", value: "rgba(0,0,0,.15)", position: 116, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-fallback-border", value: "#ccc", position: 117, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-divider-bg", value: "#e5e5e5", position: 118, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-link-color", value: "$gray-dark", position: 119, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-link-hover-color", value: "darken($gray-dark, 5%)", position: 120, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-link-hover-bg", value: "#f5f5f5", position: 121, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-link-active-color", value: "$component-active-color", position: 122, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-link-active-bg", value: "$component-active-bg", position: 123, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-link-disabled-color", value: "$gray-light", position: 124, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-header-color", value: "$gray-light", position: 125, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$dropdown-caret-color", value: "#000", position: 126, category_id: 13, framework: "bootstrap", version: "3.3"},
{name: "$screen-xs", value: "480px", position: 127, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-xs-min", value: "$screen-xs", position: 128, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-phone", value: "$screen-xs-min", position: 129, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-sm", value: "768px", position: 130, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-sm-min", value: "$screen-sm", position: 131, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-tablet", value: "$screen-sm-min", position: 132, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-md", value: "992px", position: 133, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-md-min", value: "$screen-md", position: 134, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-desktop", value: "$screen-md-min", position: 135, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-lg", value: "1200px", position: 136, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-lg-min", value: "$screen-lg", position: 137, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-lg-desktop", value: "$screen-lg-min", position: 138, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-xs-max", value: "($screen-sm-min - 1)", position: 139, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-sm-max", value: "($screen-md-min - 1)", position: 140, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$screen-md-max", value: "($screen-lg-min - 1)", position: 141, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$grid-columns", value: "12", position: 142, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$grid-gutter-width", value: "30px", position: 143, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$grid-float-breakpoint", value: "$screen-sm-min", position: 144, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$grid-float-breakpoint-max", value: "($grid-float-breakpoint - 1)", position: 145, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$container-tablet", value: "(720px + $grid-gutter-width)", position: 146, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$container-sm", value: "$container-tablet", position: 147, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$container-desktop", value: "(940px + $grid-gutter-width)", position: 148, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$container-md", value: "$container-desktop", position: 149, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$container-large-desktop", value: "(1140px + $grid-gutter-width)", position: 150, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$container-lg", value: "$container-large-desktop", position: 151, category_id: 7, framework: "bootstrap", version: "3.3"},
{name: "$navbar-height", value: "50px", position: 152, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-margin-bottom", value: "$line-height-computed", position: 153, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-border-radius", value: "$border-radius-base", position: 154, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-padding-horizontal", value: "floor(($grid-gutter-width / 2))", position: 155, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-padding-vertical", value: "(($navbar-height - $line-height-computed) / 2)", position: 156, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-collapse-max-height", value: "340px", position: 157, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-color", value: "#777", position: 158, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-bg", value: "#f8f8f8", position: 159, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-border", value: "darken($navbar-default-bg, 6.5%)", position: 160, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-link-color", value: "#777", position: 161, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-link-hover-color", value: "#333", position: 162, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-link-hover-bg", value: "transparent", position: 163, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-link-active-color", value: "#555", position: 164, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-link-active-bg", value: "darken($navbar-default-bg, 6.5%)", position: 165, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-link-disabled-color", value: "#ccc", position: 166, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-link-disabled-bg", value: "transparent", position: 167, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-brand-color", value: "$navbar-default-link-color", position: 168, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-brand-hover-color", value: "darken($navbar-default-brand-color, 10%)", position: 169, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-brand-hover-bg", value: "transparent", position: 170, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-toggle-hover-bg", value: "#ddd", position: 171, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-toggle-icon-bar-bg", value: "#888", position: 172, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-default-toggle-border-color", value: "#ddd", position: 173, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-color", value: "lighten($gray-light, 15%)", position: 174, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-bg", value: "#222", position: 175, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-border", value: "darken($navbar-inverse-bg, 10%)", position: 176, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-link-color", value: "lighten($gray-light, 15%)", position: 177, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-link-hover-color", value: "#fff", position: 178, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-link-hover-bg", value: "transparent", position: 179, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-link-active-color", value: "$navbar-inverse-link-hover-color", position: 180, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-link-active-bg", value: "darken($navbar-inverse-bg, 10%)", position: 181, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-link-disabled-color", value: "#444", position: 182, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-link-disabled-bg", value: "transparent", position: 183, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-brand-color", value: "$navbar-inverse-link-color", position: 184, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-brand-hover-color", value: "#fff", position: 185, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-brand-hover-bg", value: "transparent", position: 186, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-toggle-hover-bg", value: "#333", position: 187, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-toggle-icon-bar-bg", value: "#fff", position: 188, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$navbar-inverse-toggle-border-color", value: "#333", position: 189, category_id: 14, framework: "bootstrap", version: "3.3"},
{name: "$nav-link-padding", value: "10px 15px", position: 190, category_id: 15, framework: "bootstrap", version: "3.3"},
{name: "$nav-link-hover-bg", value: "$gray-lighter", position: 191, category_id: 15, framework: "bootstrap", version: "3.3"},
{name: "$nav-disabled-link-color", value: "$gray-light", position: 192, category_id: 15, framework: "bootstrap", version: "3.3"},
{name: "$nav-disabled-link-hover-color", value: "$gray-light", position: 193, category_id: 15, framework: "bootstrap", version: "3.3"},
{name: "$nav-tabs-border-color", value: "#ddd", position: 194, category_id: 33, framework: "bootstrap", version: "3.3"},
{name: "$nav-tabs-link-hover-border-color", value: "$gray-lighter", position: 195, category_id: 33, framework: "bootstrap", version: "3.3"},
{name: "$nav-tabs-active-link-hover-bg", value: "$body-bg", position: 196, category_id: 33, framework: "bootstrap", version: "3.3"},
{name: "$nav-tabs-active-link-hover-color", value: "$gray", position: 197, category_id: 33, framework: "bootstrap", version: "3.3"},
{name: "$nav-tabs-active-link-hover-border-color", value: "#ddd", position: 198, category_id: 33, framework: "bootstrap", version: "3.3"},
{name: "$nav-tabs-justified-link-border-color", value: "#ddd", position: 199, category_id: 33, framework: "bootstrap", version: "3.3"},
{name: "$nav-tabs-justified-active-link-border-color", value: "$body-bg", position: 200, category_id: 33, framework: "bootstrap", version: "3.3"},
{name: "$nav-pills-border-radius", value: "$border-radius-base", position: 201, category_id: 34, framework: "bootstrap", version: "3.3"},
{name: "$nav-pills-active-link-hover-bg", value: "$component-active-bg", position: 202, category_id: 34, framework: "bootstrap", version: "3.3"},
{name: "$nav-pills-active-link-hover-color", value: "$component-active-color", position: 203, category_id: 34, framework: "bootstrap", version: "3.3"},
{name: "$pagination-color", value: "$link-color", position: 204, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-bg", value: "#fff", position: 205, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-border", value: "#ddd", position: 206, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-hover-color", value: "$link-hover-color", position: 207, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-hover-bg", value: "$gray-lighter", position: 208, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-hover-border", value: "#ddd", position: 209, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-active-color", value: "#fff", position: 210, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-active-bg", value: "$brand-primary", position: 211, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-active-border", value: "$brand-primary", position: 212, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-disabled-color", value: "$gray-light", position: 213, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-disabled-bg", value: "#fff", position: 214, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pagination-disabled-border", value: "#ddd", position: 215, category_id: 16, framework: "bootstrap", version: "3.3"},
{name: "$pager-bg", value: "$pagination-bg", position: 216, category_id: 17, framework: "bootstrap", version: "3.3"},
{name: "$pager-border", value: "$pagination-border", position: 217, category_id: 17, framework: "bootstrap", version: "3.3"},
{name: "$pager-border-radius", value: "15px", position: 218, category_id: 17, framework: "bootstrap", version: "3.3"},
{name: "$pager-hover-bg", value: "$pagination-hover-bg", position: 219, category_id: 17, framework: "bootstrap", version: "3.3"},
{name: "$pager-active-bg", value: "$pagination-active-bg", position: 220, category_id: 17, framework: "bootstrap", version: "3.3"},
{name: "$pager-active-color", value: "$pagination-active-color", position: 221, category_id: 17, framework: "bootstrap", version: "3.3"},
{name: "$pager-disabled-color", value: "$pagination-disabled-color", position: 222, category_id: 17, framework: "bootstrap", version: "3.3"},
{name: "$jumbotron-padding", value: "30px", position: 223, category_id: 18, framework: "bootstrap", version: "3.3"},
{name: "$jumbotron-color", value: "inherit", position: 224, category_id: 18, framework: "bootstrap", version: "3.3"},
{name: "$jumbotron-bg", value: "$gray-lighter", position: 225, category_id: 18, framework: "bootstrap", version: "3.3"},
{name: "$jumbotron-heading-color", value: "inherit", position: 226, category_id: 18, framework: "bootstrap", version: "3.3"},
{name: "$jumbotron-font-size", value: "ceil(($font-size-base * 1.5))", position: 227, category_id: 18, framework: "bootstrap", version: "3.3"},
{name: "$jumbotron-heading-font-size", value: "ceil(($font-size-base * 4.5))", position: 228, category_id: 18, framework: "bootstrap", version: "3.3"},
{name: "$state-success-text", value: "#3c763d", position: 229, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-success-bg", value: "#dff0d8", position: 230, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-success-border", value: "darken(adjust-hue($state-success-bg, -10), 5%)", position: 231, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-info-text", value: "#31708f", position: 232, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-info-bg", value: "#d9edf7", position: 233, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-info-border", value: "darken(adjust-hue($state-info-bg, -10), 7%)", position: 234, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-warning-text", value: "#8a6d3b", position: 235, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-warning-bg", value: "#fcf8e3", position: 236, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-warning-border", value: "darken(adjust-hue($state-warning-bg, -10), 5%)", position: 237, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-danger-text", value: "#a94442", position: 238, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-danger-bg", value: "#f2dede", position: 239, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$state-danger-border", value: "darken(adjust-hue($state-danger-bg, -10), 5%)", position: 240, category_id: 19, framework: "bootstrap", version: "3.3"},
{name: "$tooltip-max-width", value: "200px", position: 241, category_id: 21, framework: "bootstrap", version: "3.3"},
{name: "$tooltip-color", value: "#fff", position: 242, category_id: 21, framework: "bootstrap", version: "3.3"},
{name: "$tooltip-bg", value: "#000", position: 243, category_id: 21, framework: "bootstrap", version: "3.3"},
{name: "$tooltip-opacity", value: "0.9", position: 244, category_id: 21, framework: "bootstrap", version: "3.3"},
{name: "$tooltip-arrow-width", value: "5px", position: 245, category_id: 21, framework: "bootstrap", version: "3.3"},
{name: "$tooltip-arrow-color", value: "$tooltip-bg", position: 246, category_id: 21, framework: "bootstrap", version: "3.3"},
{name: "$popover-bg", value: "#fff", position: 247, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$popover-max-width", value: "276px", position: 248, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$popover-border-color", value: "rgba(0,0,0,.2)", position: 249, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$popover-fallback-border-color", value: "#ccc", position: 250, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$popover-title-bg", value: "darken($popover-bg, 3%)", position: 251, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$popover-arrow-width", value: "10px", position: 252, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$popover-arrow-color", value: "$popover-bg", position: 253, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$popover-arrow-outer-width", value: "($popover-arrow-width + 1)", position: 254, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$popover-arrow-outer-color", value: "fade_in($popover-border-color, 0.05)", position: 255, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$popover-arrow-outer-fallback-color", value: "darken($popover-fallback-border-color, 20%)", position: 256, category_id: 22, framework: "bootstrap", version: "3.3"},
{name: "$label-default-bg", value: "$gray-light", position: 257, category_id: 23, framework: "bootstrap", version: "3.3"},
{name: "$label-primary-bg", value: "$brand-primary", position: 258, category_id: 23, framework: "bootstrap", version: "3.3"},
{name: "$label-success-bg", value: "$brand-success", position: 259, category_id: 23, framework: "bootstrap", version: "3.3"},
{name: "$label-info-bg", value: "$brand-info", position: 260, category_id: 23, framework: "bootstrap", version: "3.3"},
{name: "$label-warning-bg", value: "$brand-warning", position: 261, category_id: 23, framework: "bootstrap", version: "3.3"},
{name: "$label-danger-bg", value: "$brand-danger", position: 262, category_id: 23, framework: "bootstrap", version: "3.3"},
{name: "$label-color", value: "#fff", position: 263, category_id: 23, framework: "bootstrap", version: "3.3"},
{name: "$label-link-hover-color", value: "#fff", position: 264, category_id: 23, framework: "bootstrap", version: "3.3"},
{name: "$modal-inner-padding", value: "15px", position: 265, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-title-padding", value: "15px", position: 266, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-title-line-height", value: "$line-height-base", position: 267, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-content-bg", value: "#fff", position: 268, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-content-border-color", value: "rgba(0,0,0,.2)", position: 269, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-content-fallback-border-color", value: "#999", position: 270, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-backdrop-bg", value: "#000", position: 271, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-backdrop-opacity", value: "0.5", position: 272, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-header-border-color", value: "#e5e5e5", position: 273, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-footer-border-color", value: "$modal-header-border-color", position: 274, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-lg", value: "900px", position: 275, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-md", value: "600px", position: 276, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$modal-sm", value: "300px", position: 277, category_id: 24, framework: "bootstrap", version: "3.3"},
{name: "$alert-padding", value: "15px", position: 278, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-border-radius", value: "$border-radius-base", position: 279, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-link-font-weight", value: "bold", position: 280, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-success-bg", value: "$state-success-bg", position: 281, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-success-text", value: "$state-success-text", position: 282, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-success-border", value: "$state-success-border", position: 283, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-info-bg", value: "$state-info-bg", position: 284, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-info-text", value: "$state-info-text", position: 285, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-info-border", value: "$state-info-border", position: 286, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-warning-bg", value: "$state-warning-bg", position: 287, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-warning-text", value: "$state-warning-text", position: 288, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-warning-border", value: "$state-warning-border", position: 289, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-danger-bg", value: "$state-danger-bg", position: 290, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-danger-text", value: "$state-danger-text", position: 291, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$alert-danger-border", value: "$state-danger-border", position: 292, category_id: 25, framework: "bootstrap", version: "3.3"},
{name: "$progress-bg", value: "#f5f5f5", position: 293, category_id: 26, framework: "bootstrap", version: "3.3"},
{name: "$progress-bar-color", value: "#fff", position: 294, category_id: 26, framework: "bootstrap", version: "3.3"},
{name: "$progress-border-radius", value: "$border-radius-base", position: 295, category_id: 26, framework: "bootstrap", version: "3.3"},
{name: "$progress-bar-bg", value: "$brand-primary", position: 296, category_id: 26, framework: "bootstrap", version: "3.3"},
{name: "$progress-bar-success-bg", value: "$brand-success", position: 297, category_id: 26, framework: "bootstrap", version: "3.3"},
{name: "$progress-bar-warning-bg", value: "$brand-warning", position: 298, category_id: 26, framework: "bootstrap", version: "3.3"},
{name: "$progress-bar-danger-bg", value: "$brand-danger", position: 299, category_id: 26, framework: "bootstrap", version: "3.3"},
{name: "$progress-bar-info-bg", value: "$brand-info", position: 300, category_id: 26, framework: "bootstrap", version: "3.3"},
{name: "$list-group-bg", value: "#fff", position: 301, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-border", value: "#ddd", position: 302, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-border-radius", value: "$border-radius-base", position: 303, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-hover-bg", value: "#f5f5f5", position: 304, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-active-color", value: "$component-active-color", position: 305, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-active-bg", value: "$component-active-bg", position: 306, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-active-border", value: "$list-group-active-bg", position: 307, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-active-text-color", value: "lighten($list-group-active-bg, 40%)", position: 308, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-disabled-color", value: "$gray-light", position: 309, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-disabled-bg", value: "$gray-lighter", position: 310, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-disabled-text-color", value: "$list-group-disabled-color", position: 311, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-link-color", value: "#555", position: 312, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-link-hover-color", value: "$list-group-link-color", position: 313, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$list-group-link-heading-color", value: "#333", position: 314, category_id: 27, framework: "bootstrap", version: "3.3"},
{name: "$panel-bg", value: "#fff", position: 315, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-body-padding", value: "15px", position: 316, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-heading-padding", value: "10px 15px", position: 317, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-footer-padding", value: "$panel-heading-padding", position: 318, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-border-radius", value: "$border-radius-base", position: 319, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-inner-border", value: "#ddd", position: 320, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-footer-bg", value: "#f5f5f5", position: 321, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-default-text", value: "$gray-dark", position: 322, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-default-border", value: "#ddd", position: 323, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-default-heading-bg", value: "#f5f5f5", position: 324, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-primary-text", value: "#fff", position: 325, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-primary-border", value: "$brand-primary", position: 326, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-primary-heading-bg", value: "$brand-primary", position: 327, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-success-text", value: "$state-success-text", position: 328, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-success-border", value: "$state-success-border", position: 329, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-success-heading-bg", value: "$state-success-bg", position: 330, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-info-text", value: "$state-info-text", position: 331, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-info-border", value: "$state-info-border", position: 332, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-info-heading-bg", value: "$state-info-bg", position: 333, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-warning-text", value: "$state-warning-text", position: 334, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-warning-border", value: "$state-warning-border", position: 335, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-warning-heading-bg", value: "$state-warning-bg", position: 336, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-danger-text", value: "$state-danger-text", position: 337, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-danger-border", value: "$state-danger-border", position: 338, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$panel-danger-heading-bg", value: "$state-danger-bg", position: 339, category_id: 35, framework: "bootstrap", version: "3.3"},
{name: "$thumbnail-padding", value: "4px", position: 340, category_id: 28, framework: "bootstrap", version: "3.3"},
{name: "$thumbnail-bg", value: "$body-bg", position: 341, category_id: 28, framework: "bootstrap", version: "3.3"},
{name: "$thumbnail-border", value: "#ddd", position: 342, category_id: 28, framework: "bootstrap", version: "3.3"},
{name: "$thumbnail-border-radius", value: "$border-radius-base", position: 343, category_id: 28, framework: "bootstrap", version: "3.3"},
{name: "$thumbnail-caption-color", value: "$text-color", position: 344, category_id: 28, framework: "bootstrap", version: "3.3"},
{name: "$thumbnail-caption-padding", value: "9px", position: 345, category_id: 28, framework: "bootstrap", version: "3.3"},
{name: "$well-bg", value: "#f5f5f5", position: 346, category_id: 36, framework: "bootstrap", version: "3.3"},
{name: "$well-border", value: "darken($well-bg, 7%)", position: 347, category_id: 36, framework: "bootstrap", version: "3.3"},
{name: "$badge-color", value: "#fff", position: 348, category_id: 37, framework: "bootstrap", version: "3.3"},
{name: "$badge-link-hover-color", value: "#fff", position: 349, category_id: 37, framework: "bootstrap", version: "3.3"},
{name: "$badge-bg", value: "$gray-light", position: 350, category_id: 37, framework: "bootstrap", version: "3.3"},
{name: "$badge-active-color", value: "$link-color", position: 351, category_id: 37, framework: "bootstrap", version: "3.3"},
{name: "$badge-active-bg", value: "#fff", position: 352, category_id: 37, framework: "bootstrap", version: "3.3"},
{name: "$badge-font-weight", value: "bold", position: 353, category_id: 37, framework: "bootstrap", version: "3.3"},
{name: "$badge-line-height", value: "1", position: 354, category_id: 37, framework: "bootstrap", version: "3.3"},
{name: "$badge-border-radius", value: "10px", position: 355, category_id: 37, framework: "bootstrap", version: "3.3"},
{name: "$breadcrumb-padding-vertical", value: "8px", position: 356, category_id: 29, framework: "bootstrap", version: "3.3"},
{name: "$breadcrumb-padding-horizontal", value: "15px", position: 357, category_id: 29, framework: "bootstrap", version: "3.3"},
{name: "$breadcrumb-bg", value: "#f5f5f5", position: 358, category_id: 29, framework: "bootstrap", version: "3.3"},
{name: "$breadcrumb-color", value: "#ccc", position: 359, category_id: 29, framework: "bootstrap", version: "3.3"},
{name: "$breadcrumb-active-color", value: "$gray-light", position: 360, category_id: 29, framework: "bootstrap", version: "3.3"},
{name: "$breadcrumb-separator", value: "\"/\"", position: 361, category_id: 29, framework: "bootstrap", version: "3.3"},
{name: "$carousel-text-shadow", value: "0 1px 2px rgba(0,0,0,.6)", position: 362, category_id: 30, framework: "bootstrap", version: "3.3"},
{name: "$carousel-control-color", value: "#fff", position: 363, category_id: 30, framework: "bootstrap", version: "3.3"},
{name: "$carousel-control-width", value: "0.15", position: 364, category_id: 30, framework: "bootstrap", version: "3.3"},
{name: "$carousel-control-opacity", value: "0.5", position: 365, category_id: 30, framework: "bootstrap", version: "3.3"},
{name: "$carousel-control-font-size", value: "20px", position: 366, category_id: 30, framework: "bootstrap", version: "3.3"},
{name: "$carousel-indicator-active-bg", value: "#fff", position: 367, category_id: 30, framework: "bootstrap", version: "3.3"},
{name: "$carousel-indicator-border-color", value: "#fff", position: 368, category_id: 30, framework: "bootstrap", version: "3.3"},
{name: "$carousel-caption-color", value: "#fff", position: 369, category_id: 30, framework: "bootstrap", version: "3.3"},
{name: "$close-font-weight", value: "bold", position: 370, category_id: 31, framework: "bootstrap", version: "3.3"},
{name: "$close-color", value: "#000", position: 371, category_id: 31, framework: "bootstrap", version: "3.3"},
{name: "$close-text-shadow", value: "0 1px 0 #fff", position: 372, category_id: 31, framework: "bootstrap", version: "3.3"},
{name: "$code-color", value: "#c7254e", position: 373, category_id: 32, framework: "bootstrap", version: "3.3"},
{name: "$code-bg", value: "#f9f2f4", position: 374, category_id: 32, framework: "bootstrap", version: "3.3"},
{name: "$kbd-color", value: "#fff", position: 375, category_id: 32, framework: "bootstrap", version: "3.3"},
{name: "$kbd-bg", value: "#333", position: 376, category_id: 32, framework: "bootstrap", version: "3.3"},
{name: "$pre-bg", value: "#f5f5f5", position: 377, category_id: 32, framework: "bootstrap", version: "3.3"},
{name: "$pre-color", value: "$gray-dark", position: 378, category_id: 32, framework: "bootstrap", version: "3.3"},
{name: "$pre-border-color", value: "#ccc", position: 379, category_id: 32, framework: "bootstrap", version: "3.3"},
{name: "$pre-scrollable-max-height", value: "340px", position: 380, category_id: 32, framework: "bootstrap", version: "3.3"}

])
