# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create({{ name: 'Star Wars' }, { name: 'Lord of the Rings' }})
#   Character.create(name: 'Luke', movie: movies.first)

DefaultVariable.delete_all
DefaultVariable.create([
{name: "$gray-dark", value: "#373a3c !default", position: 1, framework: "bootstrap", version: "4-alpha"},
{name: "$gray", value: "#55595c !default", position: 2, framework: "bootstrap", version: "4-alpha"},
{name: "$gray-light", value: "#818a91 !default", position: 3, framework: "bootstrap", version: "4-alpha"},
{name: "$gray-lighter", value: "#eceeef !default", position: 4, framework: "bootstrap", version: "4-alpha"},
{name: "$gray-lightest", value: "#f7f7f9 !default", position: 5, framework: "bootstrap", version: "4-alpha"},
{name: "$brand-primary", value: "#0275d8 !default", position: 6, framework: "bootstrap", version: "4-alpha"},
{name: "$brand-success", value: "#5cb85c !default", position: 7, framework: "bootstrap", version: "4-alpha"},
{name: "$brand-info", value: "#5bc0de !default", position: 8, framework: "bootstrap", version: "4-alpha"},
{name: "$brand-warning", value: "#f0ad4e !default", position: 9, framework: "bootstrap", version: "4-alpha"},
{name: "$brand-danger", value: "#d9534f !default", position: 10, framework: "bootstrap", version: "4-alpha"},
{name: "$enable-flex", value: "false !default", position: 11, framework: "bootstrap", version: "4-alpha"},
{name: "$enable-rounded", value: "true !default", position: 12, framework: "bootstrap", version: "4-alpha"},
{name: "$enable-shadows", value: "false !default", position: 13, framework: "bootstrap", version: "4-alpha"},
{name: "$enable-gradients", value: "false !default", position: 14, framework: "bootstrap", version: "4-alpha"},
{name: "$enable-transitions", value: "false !default", position: 15, framework: "bootstrap", version: "4-alpha"},
{name: "$enable-hover-media-query", value: "false !default", position: 16, framework: "bootstrap", version: "4-alpha"},
{name: "$enable-grid-classes", value: "true !default", position: 17, framework: "bootstrap", version: "4-alpha"},
{name: "$enable-print-styles", value: "true !default", position: 18, framework: "bootstrap", version: "4-alpha"},
{name: "$spacer", value: "1rem !default", position: 19, framework: "bootstrap", version: "4-alpha"},
{name: "$spacer-x", value: "$spacer !default", position: 20, framework: "bootstrap", version: "4-alpha"},
{name: "$spacer-y", value: "$spacer !default", position: 21, framework: "bootstrap", version: "4-alpha"},
{name: "$border-width", value: "1px !default", position: 22, framework: "bootstrap", version: "4-alpha"},
{name: "$body-bg", value: "#fff !default", position: 23, framework: "bootstrap", version: "4-alpha"},
{name: "$body-color", value: "$gray-dark !default", position: 24, framework: "bootstrap", version: "4-alpha"},
{name: "$link-color", value: "$brand-primary !default", position: 25, framework: "bootstrap", version: "4-alpha"},
{name: "$link-decoration", value: "none !default", position: 26, framework: "bootstrap", version: "4-alpha"},
{name: "$link-hover-color", value: "darken($link-color, 15%) !default", position: 27, framework: "bootstrap", version: "4-alpha"},
{name: "$link-hover-decoration", value: "underline !default", position: 28, framework: "bootstrap", version: "4-alpha"},
{name: "$grid-columns", value: "12 !default", position: 29, framework: "bootstrap", version: "4-alpha"},
{name: "$grid-gutter-width", value: "30px !default", position: 30, framework: "bootstrap", version: "4-alpha"},
{name: "$font-family-sans-serif", value: '-apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif !default', position: 31, framework: "bootstrap", version: "4-alpha"},
{name: "$font-family-serif", value: 'Georgia, "Times New Roman", Times, serif !default', position: 32, framework: "bootstrap", version: "4-alpha"},
{name: "$font-family-monospace", value: 'Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace !default', position: 33, framework: "bootstrap", version: "4-alpha"},
{name: "$font-family-base", value: "$font-family-sans-serif !default", position: 34, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-root", value: "16px !default", position: 35, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-base", value: "1rem !default", position: 36, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-lg", value: "1.25rem !default", position: 37, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-sm", value: ".875rem !default", position: 38, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-xs", value: ".75rem !default", position: 39, framework: "bootstrap", version: "4-alpha"},
{name: "$line-height-base", value: "1.5 !default", position: 40, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-h1", value: "2.5rem !default", position: 41, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-h2", value: "2rem !default", position: 42, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-h3", value: "1.75rem !default", position: 43, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-h4", value: "1.5rem !default", position: 44, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-h5", value: "1.25rem !default", position: 45, framework: "bootstrap", version: "4-alpha"},
{name: "$font-size-h6", value: "1rem !default", position: 46, framework: "bootstrap", version: "4-alpha"},
{name: "$display1-size", value: "6rem !default", position: 47, framework: "bootstrap", version: "4-alpha"},
{name: "$display2-size", value: "5.5rem !default", position: 48, framework: "bootstrap", version: "4-alpha"},
{name: "$display3-size", value: "4.5rem !default", position: 49, framework: "bootstrap", version: "4-alpha"},
{name: "$display4-size", value: "3.5rem !default", position: 50, framework: "bootstrap", version: "4-alpha"},
{name: "$display1-weight", value: "300 !default", position: 51, framework: "bootstrap", version: "4-alpha"},
{name: "$display2-weight", value: "300 !default", position: 52, framework: "bootstrap", version: "4-alpha"},
{name: "$display3-weight", value: "300 !default", position: 53, framework: "bootstrap", version: "4-alpha"},
{name: "$display4-weight", value: "300 !default", position: 54, framework: "bootstrap", version: "4-alpha"},
{name: "$headings-margin-bottom", value: "($spacer /2) !default", position: 55, framework: "bootstrap", version: "4-alpha"},
{name: "$headings-font-family", value: "inherit !default", position: 56, framework: "bootstrap", version: "4-alpha"},
{name: "$headings-font-weight", value: "500 !default", position: 57, framework: "bootstrap", version: "4-alpha"},
{name: "$headings-line-height", value: "1.1 !default", position: 58, framework: "bootstrap", version: "4-alpha"},
{name: "$headings-color", value: "inherit !default", position: 59, framework: "bootstrap", version: "4-alpha"},
{name: "$lead-font-size", value: "1.25rem !default", position: 60, framework: "bootstrap", version: "4-alpha"},
{name: "$lead-font-weight", value: "300 !default", position: 61, framework: "bootstrap", version: "4-alpha"},
{name: "$small-font-size", value: "80% !default", position: 62, framework: "bootstrap", version: "4-alpha"},
{name: "$text-muted", value: "$gray-light !default", position: 63, framework: "bootstrap", version: "4-alpha"},
{name: "$abbr-border-color", value: "$gray-light !default", position: 64, framework: "bootstrap", version: "4-alpha"},
{name: "$blockquote-small-color", value: "$gray-light !default", position: 65, framework: "bootstrap", version: "4-alpha"},
{name: "$blockquote-font-size", value: "($font-size-base *1.25) !default", position: 66, framework: "bootstrap", version: "4-alpha"},
{name: "$blockquote-border-color", value: "$gray-lighter !default", position: 67, framework: "bootstrap", version: "4-alpha"},
{name: "$blockquote-border-width", value: ".25rem !default", position: 68, framework: "bootstrap", version: "4-alpha"},
{name: "$hr-border-color", value: "rgba(0,0,0,.1) !default", position: 69, framework: "bootstrap", version: "4-alpha"},
{name: "$hr-border-width", value: "$border-width !default", position: 70, framework: "bootstrap", version: "4-alpha"},
{name: "$mark-padding", value: ".2em !default", position: 71, framework: "bootstrap", version: "4-alpha"},
{name: "$dt-font-weight", value: "bold !default", position: 72, framework: "bootstrap", version: "4-alpha"},
{name: "$kbd-box-shadow", value: "inset 0 -.1rem 0 rgba(0,0,0,.25) !default", position: 73, framework: "bootstrap", version: "4-alpha"},
{name: "$nested-kbd-font-weight", value: "bold !default", position: 74, framework: "bootstrap", version: "4-alpha"},
{name: "$list-inline-padding", value: "5px !default", position: 75, framework: "bootstrap", version: "4-alpha"},
{name: "$line-height-lg", value: "(4 /3) !default", position: 76, framework: "bootstrap", version: "4-alpha"},
{name: "$line-height-sm", value: "1.5 !default", position: 77, framework: "bootstrap", version: "4-alpha"},
{name: "$border-radius", value: ".25rem !default", position: 78, framework: "bootstrap", version: "4-alpha"},
{name: "$border-radius-lg", value: ".3rem !default", position: 79, framework: "bootstrap", version: "4-alpha"},
{name: "$border-radius-sm", value: ".2rem !default", position: 80, framework: "bootstrap", version: "4-alpha"},
{name: "$component-active-color", value: "#fff !default", position: 81, framework: "bootstrap", version: "4-alpha"},
{name: "$component-active-bg", value: "$brand-primary !default", position: 82, framework: "bootstrap", version: "4-alpha"},
{name: "$caret-width", value: ".3em !default", position: 83, framework: "bootstrap", version: "4-alpha"},
{name: "$caret-width-lg", value: "$caret-width !default", position: 84, framework: "bootstrap", version: "4-alpha"},
{name: "$table-cell-padding", value: ".75rem !default", position: 85, framework: "bootstrap", version: "4-alpha"},
{name: "$table-sm-cell-padding", value: ".3rem !default", position: 86, framework: "bootstrap", version: "4-alpha"},
{name: "$table-bg", value: "transparent !default", position: 87, framework: "bootstrap", version: "4-alpha"},
{name: "$table-bg-accent", value: "#f9f9f9 !default", position: 88, framework: "bootstrap", version: "4-alpha"},
{name: "$table-bg-hover", value: "#f5f5f5 !default", position: 89, framework: "bootstrap", version: "4-alpha"},
{name: "$table-bg-active", value: "$table-bg-hover !default", position: 90, framework: "bootstrap", version: "4-alpha"},
{name: "$table-border-width", value: "$border-width !default", position: 91, framework: "bootstrap", version: "4-alpha"},
{name: "$table-border-color", value: "$gray-lighter !default", position: 92, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-padding-x", value: "1rem !default", position: 93, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-padding-y", value: ".5rem !default", position: 94, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-line-height", value: "1.25 !default", position: 95, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-font-weight", value: "normal !default", position: 96, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-box-shadow", value: "inset 0 1px 0 rgba(255,255,255,.15), 0 1px 1px rgba(0,0,0,.075) !default", position: 97, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-active-box-shadow", value: "inset 0 3px 5px rgba(0,0,0,.125) !default", position: 98, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-primary-color", value: "#fff !default", position: 99, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-primary-bg", value: "$brand-primary !default", position: 100, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-primary-border", value: "$btn-primary-bg !default", position: 101, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-secondary-color", value: "$gray-dark !default", position: 102, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-secondary-bg", value: "#fff !default", position: 103, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-secondary-border", value: "#ccc !default", position: 104, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-info-color", value: "#fff !default", position: 105, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-info-bg", value: "$brand-info !default", position: 106, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-info-border", value: "$btn-info-bg !default", position: 107, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-success-color", value: "#fff !default", position: 108, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-success-bg", value: "$brand-success !default", position: 109, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-success-border", value: "$btn-success-bg !default", position: 110, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-warning-color", value: "#fff !default", position: 111, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-warning-bg", value: "$brand-warning !default", position: 112, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-warning-border", value: "$btn-warning-bg !default", position: 113, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-danger-color", value: "#fff !default", position: 114, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-danger-bg", value: "$brand-danger !default", position: 115, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-danger-border", value: "$btn-danger-bg !default", position: 116, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-link-disabled-color", value: "$gray-light !default", position: 117, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-padding-x-sm", value: ".5rem !default", position: 118, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-padding-y-sm", value: ".25rem !default", position: 119, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-padding-x-lg", value: "1.5rem !default", position: 120, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-padding-y-lg", value: ".75rem !default", position: 121, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-block-spacing-y", value: "5px !default", position: 122, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-toolbar-margin", value: "5px !default", position: 123, framework: "bootstrap", version: "4-alpha"},
{name: "$split-btn-dropdown-toggle-padding-x", value: "8px !default", position: 124, framework: "bootstrap", version: "4-alpha"},
{name: "$split-btn-lg-dropdown-toggle-padding-x", value: "12px !default", position: 125, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-border-radius", value: "$border-radius !default", position: 126, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-border-radius-lg", value: "$border-radius-lg !default", position: 127, framework: "bootstrap", version: "4-alpha"},
{name: "$btn-border-radius-sm", value: "$border-radius-sm !default", position: 128, framework: "bootstrap", version: "4-alpha"},
{name: "$input-padding-x", value: ".75rem !default", position: 129, framework: "bootstrap", version: "4-alpha"},
{name: "$input-padding-y", value: ".5rem !default", position: 130, framework: "bootstrap", version: "4-alpha"},
{name: "$input-line-height", value: "1.25 !default", position: 131, framework: "bootstrap", version: "4-alpha"},
{name: "$input-bg", value: "#fff !default", position: 132, framework: "bootstrap", version: "4-alpha"},
{name: "$input-bg-disabled", value: "$gray-lighter !default", position: 133, framework: "bootstrap", version: "4-alpha"},
{name: "$input-color", value: "$gray !default", position: 134, framework: "bootstrap", version: "4-alpha"},
{name: "$input-border-color", value: "rgba(0,0,0,.15) !default", position: 135, framework: "bootstrap", version: "4-alpha"},
{name: "$input-btn-border-width", value: "$border-width !default", position: 136, framework: "bootstrap", version: "4-alpha"},
{name: "$input-box-shadow", value: "inset 0 1px 1px rgba(0,0,0,.075) !default", position: 137, framework: "bootstrap", version: "4-alpha"},
{name: "$input-border-radius", value: "$border-radius !default", position: 138, framework: "bootstrap", version: "4-alpha"},
{name: "$input-border-radius-lg", value: "$border-radius-lg !default", position: 139, framework: "bootstrap", version: "4-alpha"},
{name: "$input-border-radius-sm", value: "$border-radius-sm !default", position: 140, framework: "bootstrap", version: "4-alpha"},
{name: "$input-border-focus", value: "#66afe9 !default", position: 141, framework: "bootstrap", version: "4-alpha"},
{name: "$input-box-shadow-focus", value: "rgba(102,175,233,.6) !default", position: 142, framework: "bootstrap", version: "4-alpha"},
{name: "$input-color-placeholder", value: "#999 !default", position: 143, framework: "bootstrap", version: "4-alpha"},
{name: "$input-padding-x-sm", value: ".5rem !default", position: 144, framework: "bootstrap", version: "4-alpha"},
{name: "$input-padding-y-sm", value: ".25rem !default", position: 145, framework: "bootstrap", version: "4-alpha"},
{name: "$input-padding-x-lg", value: "1.5rem !default", position: 146, framework: "bootstrap", version: "4-alpha"},
{name: "$input-padding-y-lg", value: ".75rem !default", position: 147, framework: "bootstrap", version: "4-alpha"},
{name: "$input-height", value: "(($font-size-base * $line-height-base) + ($input-padding-y *2)) !default", position: 148, framework: "bootstrap", version: "4-alpha"},
{name: "$input-height-lg", value: "(($font-size-lg * $line-height-lg) + ($input-padding-y-lg *2)) !default", position: 149, framework: "bootstrap", version: "4-alpha"},
{name: "$input-height-sm", value: "(($font-size-sm * $line-height-sm) + ($input-padding-y-sm *2)) !default", position: 150, framework: "bootstrap", version: "4-alpha"},
{name: "$form-group-margin-bottom", value: "$spacer-y !default", position: 151, framework: "bootstrap", version: "4-alpha"},
{name: "$input-group-addon-bg", value: "$gray-lighter !default", position: 152, framework: "bootstrap", version: "4-alpha"},
{name: "$input-group-addon-border-color", value: "$input-border-color !default", position: 153, framework: "bootstrap", version: "4-alpha"},
{name: "$cursor-disabled", value: "not-allowed !default", position: 154, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-gutter", value: "1.5rem !default", position: 155, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-spacer-x", value: "1rem !default", position: 156, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-spacer-y", value: ".25rem !default", position: 157, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-indicator-size", value: "1rem !default", position: 158, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-indicator-bg", value: "#ddd !default", position: 159, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-indicator-bg-size", value: "50%50% !default", position: 160, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-indicator-box-shadow", value: "inset 0 .25rem .25rem rgba(0,0,0,.1) !default", position: 161, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-disabled-cursor", value: "$cursor-disabled !default", position: 162, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-disabled-indicator-bg", value: "#eee !default", position: 163, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-disabled-description-color", value: "#767676 !default", position: 164, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-checked-indicator-color", value: "#fff !default", position: 165, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-checked-indicator-bg", value: "#0074d9 !default", position: 166, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-checked-indicator-box-shadow", value: "none !default", position: 167, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-focus-indicator-box-shadow", value: "0 0 0 .075rem #fff, 0 0 0 .2rem #0074d9 !default", position: 168, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-active-indicator-color", value: "#fff !default", position: 169, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-active-indicator-bg", value: "#84c6ff !default", position: 170, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-control-active-indicator-box-shadow", value: "none !default", position: 171, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-checkbox-radius", value: "$border-radius !default", position: 172, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-checkbox-checked-icon", value: "url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cpath fill='%23fff' d='M6.564.75l-3.59 3.612-1.538-1.55L0 4.26 2.974 7.25 8 2.193z'/%3E%3C/svg%3E\") !default", position: 173, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-checkbox-indeterminate-bg", value: "#0074d9 !default", position: 174, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-checkbox-indeterminate-icon", value: "url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 4'%3E%3Cpath stroke='%23fff' d='M0 2h4'/%3E%3C/svg%3E\") !default", position: 175, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-checkbox-indeterminate-box-shadow", value: "none !default", position: 176, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-radio-radius", value: "50% !default", position: 177, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-radio-checked-icon", value: "url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3E%3Ccircle r='3' fill='%23fff'/%3E%3C/svg%3E\") !default", position: 178, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-padding-x", value: ".75rem !default", position: 179, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-padding-y", value: ".375rem !default", position: 180, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-indicator-padding", value: "1rem !default", position: 181, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-color", value: "$input-color !default", position: 182, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-bg", value: "#fff !default", position: 183, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-bg-size", value: "8px10px !default", position: 184, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-indicator", value: "url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3E%3Cpath fill='%23333' d='M2 0L0 2h4zm0 5L0 3h4z'/%3E%3C/svg%3E\") !default", position: 185, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-border-width", value: "$input-btn-border-width !default", position: 186, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-border-color", value: "$input-border-color !default", position: 187, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-border-radius", value: "$border-radius !default", position: 188, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-focus-border-color", value: "#51a7e8 !default", position: 189, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-focus-box-shadow", value: "inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 5px rgba(81, 167, 232, .5) !default", position: 190, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-sm-padding-y", value: ".2rem !default", position: 191, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-select-sm-font-size", value: "75% !default", position: 192, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-height", value: "2.5rem !default", position: 193, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-width", value: "14rem !default", position: 194, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-focus-box-shadow", value: "0 0 0 .075rem #fff, 0 0 0 .2rem #0074d9 !default", position: 195, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-padding-x", value: ".5rem !default", position: 196, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-padding-y", value: "1rem !default", position: 197, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-line-height", value: "1.5 !default", position: 198, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-color", value: "#555 !default", position: 199, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-bg", value: "#fff !default", position: 200, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-border-width", value: "$border-width !default", position: 201, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-border-color", value: "#ddd !default", position: 202, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-border-radius", value: "$border-radius !default", position: 203, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-box-shadow", value: "inset 0 .2rem .4rem rgba(0,0,0,.05) !default", position: 204, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-button-color", value: "$custom-file-color !default", position: 205, framework: "bootstrap", version: "4-alpha"},
{name: "$custom-file-button-bg", value: "#eee !default", position: 206, framework: "bootstrap", version: "4-alpha"},
{name: "$form-icon-success", value: "url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cpath fill='%235cb85c' d='M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3E%3C/svg%3E\") !default", position: 207, framework: "bootstrap", version: "4-alpha"},
{name: "$form-icon-warning", value: "url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cpath fill='%23f0ad4e' d='M4.4 5.324h-.8v-2.46h.8zm0 1.42h-.8V5.89h.8zM3.76.63L.04 7.075c-.115.2.016.425.26.426h7.397c.242 0 .372-.226.258-.426C6.726 4.924 5.47 2.79 4.253.63c-.113-.174-.39-.174-.494 0z'/%3E%3C/svg%3E\") !default", position: 208, framework: "bootstrap", version: "4-alpha"},
{name: "$form-icon-danger", value: "url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23d9534f' viewBox='-2 -2 7 7'%3E%3Cpath stroke='%23d9534f' d='M0 0l3 3m0-3L0 3'/%3E%3Ccircle r='.5'/%3E%3Ccircle cx='3' r='.5'/%3E%3Ccircle cy='3' r='.5'/%3E%3Ccircle cx='3' cy='3' r='.5'/%3E%3C/svg%3E\") !default", position: 209, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-min-width", value: "160px !default", position: 210, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-padding-y", value: "5px !default", position: 211, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-margin-top", value: "2px !default", position: 212, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-bg", value: "#fff !default", position: 213, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-border-color", value: "rgba(0,0,0,.15) !default", position: 214, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-border-width", value: "$border-width !default", position: 215, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-divider-bg", value: "#e5e5e5 !default", position: 216, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-box-shadow", value: "0 6px 12px rgba(0,0,0,.175) !default", position: 217, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-link-color", value: "$gray-dark !default", position: 218, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-link-hover-color", value: "darken($gray-dark, 5%) !default", position: 219, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-link-hover-bg", value: "#f5f5f5 !default", position: 220, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-link-active-color", value: "$component-active-color !default", position: 221, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-link-active-bg", value: "$component-active-bg !default", position: 222, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-link-disabled-color", value: "$gray-light !default", position: 223, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-item-padding-x", value: "20px !default", position: 224, framework: "bootstrap", version: "4-alpha"},
{name: "$dropdown-header-color", value: "$gray-light !default", position: 225, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-border-radius", value: "$border-radius !default", position: 226, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-padding-x", value: "$spacer !default", position: 227, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-padding-y", value: "($spacer /2) !default", position: 228, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-brand-padding-y", value: ".25rem !default", position: 229, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-dark-color", value: "rgba(255,255,255,.5) !default", position: 230, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-dark-hover-color", value: "rgba(255,255,255,.75) !default", position: 231, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-dark-active-color", value: "rgba(255,255,255,1) !default", position: 232, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-dark-disabled-color", value: "rgba(255,255,255,.25) !default", position: 233, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-light-color", value: "rgba(0,0,0,.3) !default", position: 234, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-light-hover-color", value: "rgba(0,0,0,.6) !default", position: 235, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-light-active-color", value: "rgba(0,0,0,.8) !default", position: 236, framework: "bootstrap", version: "4-alpha"},
{name: "$navbar-light-disabled-color", value: "rgba(0,0,0,.15) !default", position: 237, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-item-margin", value: ".2rem !default", position: 238, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-item-inline-spacer", value: "1rem !default", position: 239, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-link-padding", value: ".5em 1em !default", position: 240, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-link-hover-bg", value: "$gray-lighter !default", position: 241, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-disabled-link-color", value: "$gray-light !default", position: 242, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-disabled-link-hover-color", value: "$gray-light !default", position: 243, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-disabled-link-hover-bg", value: "transparent !default", position: 244, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-tabs-border-color", value: "#ddd !default", position: 245, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-tabs-border-width", value: "$border-width !default", position: 246, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-tabs-link-hover-border-color", value: "$gray-lighter !default", position: 247, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-tabs-active-link-hover-color", value: "$gray !default", position: 248, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-tabs-active-link-hover-bg", value: "$body-bg !default", position: 249, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-tabs-active-link-hover-border-color", value: "#ddd !default", position: 250, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-tabs-justified-link-border-color", value: "#ddd !default", position: 251, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-tabs-justified-active-link-border-color", value: "$body-bg !default", position: 252, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-pills-border-radius", value: "$border-radius !default", position: 253, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-pills-active-link-color", value: "$component-active-color !default", position: 254, framework: "bootstrap", version: "4-alpha"},
{name: "$nav-pills-active-link-bg", value: "$component-active-bg !default", position: 255, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-padding-x", value: ".75rem !default", position: 256, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-padding-y", value: ".5rem !default", position: 257, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-padding-x-sm", value: ".75rem !default", position: 258, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-padding-y-sm", value: ".275rem !default", position: 259, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-padding-x-lg", value: "1.5rem !default", position: 260, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-padding-y-lg", value: ".75rem !default", position: 261, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-color", value: "$link-color !default", position: 262, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-bg", value: "#fff !default", position: 263, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-border-width", value: "$border-width !default", position: 264, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-border-color", value: "#ddd !default", position: 265, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-hover-color", value: "$link-hover-color !default", position: 266, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-hover-bg", value: "$gray-lighter !default", position: 267, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-hover-border", value: "#ddd !default", position: 268, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-active-color", value: "#fff !default", position: 269, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-active-bg", value: "$brand-primary !default", position: 270, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-active-border", value: "$brand-primary !default", position: 271, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-disabled-color", value: "$gray-light !default", position: 272, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-disabled-bg", value: "#fff !default", position: 273, framework: "bootstrap", version: "4-alpha"},
{name: "$pagination-disabled-border", value: "#ddd !default", position: 274, framework: "bootstrap", version: "4-alpha"},
{name: "$jumbotron-padding", value: "2rem !default", position: 275, framework: "bootstrap", version: "4-alpha"},
{name: "$jumbotron-bg", value: "$gray-lighter !default", position: 276, framework: "bootstrap", version: "4-alpha"},
{name: "$state-success-text", value: "#3c763d !default", position: 277, framework: "bootstrap", version: "4-alpha"},
{name: "$state-success-bg", value: "#dff0d8 !default", position: 278, framework: "bootstrap", version: "4-alpha"},
{name: "$state-success-border", value: "darken($state-success-bg, 5%) !default", position: 279, framework: "bootstrap", version: "4-alpha"},
{name: "$state-info-text", value: "#31708f !default", position: 280, framework: "bootstrap", version: "4-alpha"},
{name: "$state-info-bg", value: "#d9edf7 !default", position: 281, framework: "bootstrap", version: "4-alpha"},
{name: "$state-info-border", value: "darken($state-info-bg, 7%) !default", position: 282, framework: "bootstrap", version: "4-alpha"},
{name: "$state-warning-text", value: "#8a6d3b !default", position: 283, framework: "bootstrap", version: "4-alpha"},
{name: "$state-warning-bg", value: "#fcf8e3 !default", position: 284, framework: "bootstrap", version: "4-alpha"},
{name: "$mark-bg", value: "$state-warning-bg !default", position: 285, framework: "bootstrap", version: "4-alpha"},
{name: "$state-warning-border", value: "darken($state-warning-bg, 5%) !default", position: 286, framework: "bootstrap", version: "4-alpha"},
{name: "$state-danger-text", value: "#a94442 !default", position: 287, framework: "bootstrap", version: "4-alpha"},
{name: "$state-danger-bg", value: "#f2dede !default", position: 288, framework: "bootstrap", version: "4-alpha"},
{name: "$state-danger-border", value: "darken($state-danger-bg, 5%) !default", position: 289, framework: "bootstrap", version: "4-alpha"},
{name: "$card-spacer-x", value: "1.25rem !default", position: 290, framework: "bootstrap", version: "4-alpha"},
{name: "$card-spacer-y", value: ".75rem !default", position: 291, framework: "bootstrap", version: "4-alpha"},
{name: "$card-border-width", value: "1px !default", position: 292, framework: "bootstrap", version: "4-alpha"},
{name: "$card-border-radius", value: "$border-radius !default", position: 293, framework: "bootstrap", version: "4-alpha"},
{name: "$card-border-color", value: "rgba(0,0,0,.125) !default", position: 294, framework: "bootstrap", version: "4-alpha"},
{name: "$card-border-radius-inner", value: "$card-border-radius !default", position: 295, framework: "bootstrap", version: "4-alpha"},
{name: "$card-cap-bg", value: "#f5f5f5 !default", position: 296, framework: "bootstrap", version: "4-alpha"},
{name: "$card-bg", value: "#fff !default", position: 297, framework: "bootstrap", version: "4-alpha"},
{name: "$card-link-hover-color", value: "#fff !default", position: 298, framework: "bootstrap", version: "4-alpha"},
{name: "$card-deck-margin", value: ".625rem !default", position: 299, framework: "bootstrap", version: "4-alpha"},
{name: "$card-columns-sm-up-column-gap", value: "1.25rem !default", position: 300, framework: "bootstrap", version: "4-alpha"},
{name: "$tooltip-max-width", value: "200px !default", position: 301, framework: "bootstrap", version: "4-alpha"},
{name: "$tooltip-color", value: "#fff !default", position: 302, framework: "bootstrap", version: "4-alpha"},
{name: "$tooltip-bg", value: "#000 !default", position: 303, framework: "bootstrap", version: "4-alpha"},
{name: "$tooltip-opacity", value: ".9 !default", position: 304, framework: "bootstrap", version: "4-alpha"},
{name: "$tooltip-padding-y", value: "3px !default", position: 305, framework: "bootstrap", version: "4-alpha"},
{name: "$tooltip-padding-x", value: "8px !default", position: 306, framework: "bootstrap", version: "4-alpha"},
{name: "$tooltip-margin", value: "3px !default", position: 307, framework: "bootstrap", version: "4-alpha"},
{name: "$tooltip-arrow-width", value: "5px !default", position: 308, framework: "bootstrap", version: "4-alpha"},
{name: "$tooltip-arrow-color", value: "$tooltip-bg !default", position: 309, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-bg", value: "#fff !default", position: 310, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-max-width", value: "276px !default", position: 311, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-border-width", value: "$border-width !default", position: 312, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-border-color", value: "rgba(0,0,0,.2) !default", position: 313, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-box-shadow", value: "0 5px 10px rgba(0,0,0,.2) !default", position: 314, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-title-bg", value: "darken($popover-bg, 3%) !default", position: 315, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-title-padding-x", value: "14px !default", position: 316, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-title-padding-y", value: "8px !default", position: 317, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-content-padding-x", value: "14px !default", position: 318, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-content-padding-y", value: "9px !default", position: 319, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-arrow-width", value: "10px !default", position: 320, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-arrow-color", value: "$popover-bg !default", position: 321, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-arrow-outer-width", value: "($popover-arrow-width + 1px) !default", position: 322, framework: "bootstrap", version: "4-alpha"},
{name: "$popover-arrow-outer-color", value: "fade-in($popover-border-color, .05) !default", position: 323, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-default-bg", value: "$gray-light !default", position: 324, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-primary-bg", value: "$brand-primary !default", position: 325, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-success-bg", value: "$brand-success !default", position: 326, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-info-bg", value: "$brand-info !default", position: 327, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-warning-bg", value: "$brand-warning !default", position: 328, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-danger-bg", value: "$brand-danger !default", position: 329, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-color", value: "#fff !default", position: 330, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-link-hover-color", value: "#fff !default", position: 331, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-font-size", value: "75% !default", position: 332, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-font-weight", value: "bold !default", position: 333, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-padding-x", value: ".4em !default", position: 334, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-padding-y", value: ".25em !default", position: 335, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-pill-padding-x", value: ".6em !default", position: 336, framework: "bootstrap", version: "4-alpha"},
{name: "$tag-pill-border-radius", value: "10rem !default", position: 337, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-inner-padding", value: "15px !default", position: 338, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-dialog-margin", value: "10px !default", position: 339, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-dialog-sm-up-margin-y", value: "30px !default", position: 340, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-title-padding", value: "15px !default", position: 341, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-title-line-height", value: "$line-height-base !default", position: 342, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-content-bg", value: "#fff !default", position: 343, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-content-border-color", value: "rgba(0,0,0,.2) !default;", position: 344, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-content-border-width", value: "$border-width !default", position: 345, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-content-xs-box-shadow", value: "0 3px 9px rgba(0,0,0,.5) !default", position: 346, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-content-sm-up-box-shadow", value: "0 5px 15px rgba(0,0,0,.5) !default", position: 347, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-backdrop-bg", value: "#000 !default", position: 348, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-backdrop-opacity", value: ".5 !default", position: 349, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-header-border-color", value: "#e5e5e5 !default", position: 350, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-footer-border-color", value: "$modal-header-border-color !default", position: 351, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-header-border-width", value: "$modal-content-border-width !default", position: 352, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-footer-border-width", value: "$modal-header-border-width !default", position: 353, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-lg", value: "900px !default", position: 354, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-md", value: "600px !default", position: 355, framework: "bootstrap", version: "4-alpha"},
{name: "$modal-sm", value: "300px !default", position: 356, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-padding", value: "15px !default", position: 357, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-border-radius", value: "$border-radius !default", position: 358, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-link-font-weight", value: "bold !default", position: 359, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-border-width", value: "$border-width !default", position: 360, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-success-bg", value: "$state-success-bg !default", position: 361, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-success-text", value: "$state-success-text !default", position: 362, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-success-border", value: "$state-success-border !default", position: 363, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-info-bg", value: "$state-info-bg !default", position: 364, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-info-text", value: "$state-info-text !default", position: 365, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-info-border", value: "$state-info-border !default", position: 366, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-warning-bg", value: "$state-warning-bg !default", position: 367, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-warning-text", value: "$state-warning-text !default", position: 368, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-warning-border", value: "$state-warning-border !default", position: 369, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-danger-bg", value: "$state-danger-bg !default", position: 370, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-danger-text", value: "$state-danger-text !default", position: 371, framework: "bootstrap", version: "4-alpha"},
{name: "$alert-danger-border", value: "$state-danger-border !default", position: 372, framework: "bootstrap", version: "4-alpha"},
{name: "$progress-bg", value: "#eee !default", position: 373, framework: "bootstrap", version: "4-alpha"},
{name: "$progress-bar-color", value: "#0074d9 !default", position: 374, framework: "bootstrap", version: "4-alpha"},
{name: "$progress-border-radius", value: "$border-radius !default", position: 375, framework: "bootstrap", version: "4-alpha"},
{name: "$progress-box-shadow", value: "inset 0 .1rem .1rem rgba(0,0,0,.1) !default", position: 376, framework: "bootstrap", version: "4-alpha"},
{name: "$progress-bar-bg", value: "$brand-primary !default", position: 377, framework: "bootstrap", version: "4-alpha"},
{name: "$progress-bar-success-bg", value: "$brand-success !default", position: 378, framework: "bootstrap", version: "4-alpha"},
{name: "$progress-bar-warning-bg", value: "$brand-warning !default", position: 379, framework: "bootstrap", version: "4-alpha"},
{name: "$progress-bar-danger-bg", value: "$brand-danger !default", position: 380, framework: "bootstrap", version: "4-alpha"},
{name: "$progress-bar-info-bg", value: "$brand-info !default", position: 381, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-bg", value: "#fff !default", position: 382, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-border-color", value: "#ddd !default", position: 383, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-border-width", value: "$border-width !default", position: 384, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-border-radius", value: "$border-radius !default", position: 385, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-hover-bg", value: "#f5f5f5 !default", position: 386, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-active-color", value: "$component-active-color !default", position: 387, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-active-bg", value: "$component-active-bg !default", position: 388, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-active-border", value: "$list-group-active-bg !default", position: 389, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-active-text-color", value: "lighten($list-group-active-bg, 40%) !default", position: 390, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-disabled-color", value: "$gray-light !default", position: 391, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-disabled-bg", value: "$gray-lighter !default", position: 392, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-disabled-text-color", value: "$list-group-disabled-color !default", position: 393, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-link-color", value: "#555 !default", position: 394, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-link-hover-color", value: "$list-group-link-color !default", position: 395, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-link-heading-color", value: "#333 !default", position: 396, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-item-padding-x", value: "1.25rem !default", position: 397, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-item-padding-y", value: ".75rem !default", position: 398, framework: "bootstrap", version: "4-alpha"},
{name: "$list-group-item-heading-margin-bottom", value: "5px !default", position: 399, framework: "bootstrap", version: "4-alpha"},
{name: "$thumbnail-padding", value: ".25rem !default", position: 400, framework: "bootstrap", version: "4-alpha"},
{name: "$thumbnail-bg", value: "$body-bg !default", position: 401, framework: "bootstrap", version: "4-alpha"},
{name: "$thumbnail-border-width", value: "$border-width !default", position: 402, framework: "bootstrap", version: "4-alpha"},
{name: "$thumbnail-border-color", value: "#ddd !default", position: 403, framework: "bootstrap", version: "4-alpha"},
{name: "$thumbnail-border-radius", value: "$border-radius !default", position: 404, framework: "bootstrap", version: "4-alpha"},
{name: "$thumbnail-box-shadow", value: "0 1px 2px rgba(0,0,0,.075) !default", position: 405, framework: "bootstrap", version: "4-alpha"},
{name: "$figure-caption-font-size", value: "90% !default", position: 406, framework: "bootstrap", version: "4-alpha"},
{name: "$breadcrumb-padding-y", value: ".75rem !default", position: 407, framework: "bootstrap", version: "4-alpha"},
{name: "$breadcrumb-padding-x", value: "1rem !default", position: 408, framework: "bootstrap", version: "4-alpha"},
{name: "$breadcrumb-item-padding", value: ".5rem !default", position: 409, framework: "bootstrap", version: "4-alpha"},
{name: "$breadcrumb-bg", value: "$gray-lighter !default", position: 410, framework: "bootstrap", version: "4-alpha"},
{name: "$breadcrumb-divider-color", value: "$gray-light !default", position: 411, framework: "bootstrap", version: "4-alpha"},
{name: "$breadcrumb-active-color", value: "$gray-light !default", position: 412, framework: "bootstrap", version: "4-alpha"},
{name: "$breadcrumb-divider", value: '"/" !default', position: 413, framework: "bootstrap", version: "4-alpha"},
{name: "$media-margin-top", value: "15px !default", position: 414, framework: "bootstrap", version: "4-alpha"},
{name: "$media-heading-margin-bottom", value: "5px !default", position: 415, framework: "bootstrap", version: "4-alpha"},
{name: "$media-alignment-padding-x", value: "10px !default", position: 416, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-text-shadow", value: "0 1px 2px rgba(0,0,0,.6) !default", position: 417, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-control-color", value: "#fff !default", position: 418, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-control-width", value: "15% !default", position: 419, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-control-sm-up-size", value: "30px !default", position: 420, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-control-opacity", value: ".5 !default", position: 421, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-control-font-size", value: "20px !default", position: 422, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-indicators-width", value: "60% !default", position: 423, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-indicator-size", value: "10px !default", position: 424, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-indicator-active-size", value: "12px !default", position: 425, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-indicator-active-bg", value: "#fff !default", position: 426, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-indicator-border-color", value: "#fff !default", position: 427, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-caption-width", value: "70% !default", position: 428, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-caption-sm-up-width", value: "60% !default", position: 429, framework: "bootstrap", version: "4-alpha"},
{name: "$carousel-caption-color", value: "#fff !default", position: 430, framework: "bootstrap", version: "4-alpha"},
{name: "$close-font-weight", value: "bold !default", position: 431, framework: "bootstrap", version: "4-alpha"},
{name: "$close-color", value: "#000 !default", position: 432, framework: "bootstrap", version: "4-alpha"},
{name: "$close-text-shadow", value: "0 1px 0 #fff !default", position: 433, framework: "bootstrap", version: "4-alpha"},
{name: "$code-font-size", value: "90% !default", position: 434, framework: "bootstrap", version: "4-alpha"},
{name: "$code-padding-x", value: ".4rem !default", position: 435, framework: "bootstrap", version: "4-alpha"},
{name: "$code-padding-y", value: ".2rem !default", position: 436, framework: "bootstrap", version: "4-alpha"},
{name: "$code-color", value: "#bd4147 !default", position: 437, framework: "bootstrap", version: "4-alpha"},
{name: "$code-bg", value: "#f7f7f9 !default", position: 438, framework: "bootstrap", version: "4-alpha"},
{name: "$kbd-color", value: "#fff !default", position: 439, framework: "bootstrap", version: "4-alpha"},
{name: "$kbd-bg", value: "#333 !default", position: 440, framework: "bootstrap", version: "4-alpha"},
{name: "$pre-bg", value: "#f7f7f9 !default", position: 441, framework: "bootstrap", version: "4-alpha"},
{name: "$pre-color", value: "$gray-dark !default", position: 442, framework: "bootstrap", version: "4-alpha"},
{name: "$pre-border-color", value: "#ccc !default", position: 443, framework: "bootstrap", version: "4-alpha"},
{name: "$pre-scrollable-max-height", value: "340px !default", position: 444, framework: "bootstrap", version: "4-alpha"}
])
